---
sidebar: sidebar 
permalink: concept-install-options-aws.html 
keywords: install connector aws, aws install connector, connector aws, aws connector, installation options, aws marketplace, manual install, deploy 
summary: Hay algunas formas diferentes de crear un agente de consola en AWS.  La forma más común es hacerlo directamente desde la NetApp Console . 
---
= Opciones de instalación del agente de consola en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay algunas formas diferentes de crear un agente de consola en AWS.  La forma más común es hacerlo directamente desde la NetApp Console .

Están disponibles las siguientes opciones de instalación:

* link:task-install-agent-aws-console.html["Cree el agente de la consola directamente desde la consola"](esta es la opción estándar)
+
Esta acción inicia una instancia EC2 que ejecuta Linux y el software del agente de consola en una VPC de su elección.

* link:task-install-agent-aws-marketplace.html["Cree un agente de consola desde AWS Marketplace"]
+
Esta acción también inicia una instancia EC2 que ejecuta Linux y el software del agente de consola, pero la implementación se inicia directamente desde AWS Marketplace, en lugar de desde la consola.

* link:task-install-agent-aws-manual.html["Descargue e instale manualmente el software en su propio host Linux"]


La opción de instalación que elija afectará su forma de prepararse para la instalación.  Esto incluye cómo proporcionar a la consola los permisos necesarios para autenticar y administrar recursos en AWS.
