---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Utilice un agente de consola para conectar NetApp Console a su infraestructura y orquestar de forma segura soluciones de almacenamiento en AWS, Azure, Google Cloud o entornos locales, además de utilizar proveedores de protección de datos. 
---
= Obtenga más información sobre los agentes de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice un agente de consola para conectar NetApp Console a su infraestructura y orquestar de forma segura soluciones de almacenamiento en AWS, Azure, Google Cloud o entornos locales, además de utilizar servicios de protección de datos.

Un agente de consola le permite:

* Organice tareas de administración de almacenamiento desde la NetApp Console, como el aprovisionamiento de Cloud Volumes ONTAP, la configuración de volúmenes de almacenamiento, el uso de la clasificación de datos y más.
* Autenticación mediante los roles IAM de su proveedor de nube para la integración de facturación de suscripciones
* Utilice servicios de datos avanzados (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience y NetApp Cloud Tiering)
* Utilice la consola en modo restringido.


Si no necesita orquestación avanzada ni protección de datos, puede administrar de forma centralizada los clústeres ONTAP locales y los servicios de almacenamiento nativos de la nube sin implementar un agente. También están disponibles herramientas de monitorización y movilidad de datos.

La siguiente tabla muestra qué funciones y servicios puede utilizar con y sin un agente de consola.

[cols="40,20a,20a"]
|===
|  | Disponible con agente | Disponible sin agente 


3+| *Sistemas de almacenamiento compatibles*: 


| Amazon FSx para ONTAP  a| 
Sí (funciones de descubrimiento y gestión)
 a| 
Sí (sólo descubrimiento)



| Almacenamiento de Amazon S3  a| 
Sí
 a| 
No



| Almacenamiento de blobs de Azure  a| 
Sí
 a| 
Sí



| Azure NetApp Files  a| 
Sí
 a| 
Sí



| Cloud Volumes ONTAP  a| 
Sí
 a| 
No



| Sistemas de la serie E  a| 
Sí
 a| 
No



| Google Cloud NetApp Volumes  a| 
Sí
 a| 
Sí



| Depósitos de almacenamiento de Google Cloud  a| 
Sí
 a| 
No



| Sistemas StorageGRID  a| 
Sí
 a| 
No



| Clúster ONTAP local (gestión y descubrimiento avanzados)  a| 
Sí (gestión y descubrimiento avanzados)
 a| 
No (sólo descubrimiento básico)



3+| *Servicios de gestión de almacenamiento disponibles*: 


| Alertas  a| 
Sí
 a| 
No



| Centro de automatización  a| 
Sí
 a| 
Sí



| Digital Advisor (Active IQ)  a| 
Sí
 a| 
No



| Gestión de licencias y suscripciones  a| 
Sí
 a| 
No



| Eficiencia económica  a| 
Sí
 a| 
No



| Métricas del panel de la página de inicio  a| 
Sí^2^
 a| 
No



| Planificación del ciclo de vida  a| 
Sí
 a| 
No^1^



| Sostenibilidad  a| 
Sí
 a| 
No



| Actualizaciones de software  a| 
Sí
 a| 
Sí



| Cargas de trabajo de NetApp  a| 
Sí
 a| 
Sí



3+| *Servicios de datos disponibles*: 


| NetApp Backup and Recovery  a| 
Sí
 a| 
No



| Clasificación de datos  a| 
Sí
 a| 
No



| NetApp Cloud Tiering  a| 
Sí
 a| 
No



| NetApp Copy and Sync  a| 
Sí
 a| 
No



| NetApp Disaster Recovery  a| 
Sí
 a| 
No



| NetApp Ransomware Resilience  a| 
Sí
 a| 
No



| NetApp Volume Caching  a| 
Sí
 a| 
No

|===
^1^ Puede ver la planificación del ciclo de vida sin un agente de consola, pero se requiere un agente de consola para iniciar acciones.

^2^ Las métricas precisas en la página de inicio requieren agentes de consola configurados y de tamaño adecuado.



== Los agentes de consola deben estar operativos en todo momento

Los agentes de consola son una parte fundamental de la NetApp Console.  Es su responsabilidad (la del cliente) asegurarse de que los agentes relevantes estén disponibles, operativos y accesibles en todo momento.  La consola puede manejar interrupciones breves del agente, pero debe solucionar las fallas de infraestructura rápidamente.

Esta documentación se rige por el EULA.  Utilizar el producto fuera de la documentación puede afectar su funcionalidad y sus derechos de EULA.



== Ubicaciones compatibles

Puede instalar agentes en las siguientes ubicaciones:

* Servicios web de Amazon
* Microsoft Azure
+
Implemente un agente de consola en Azure en la misma región que los sistemas Cloud Volumes ONTAP que administra.  Alternativamente, impleméntelo en el https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiones de Azure"^] .  Esto garantiza que se utilice una conexión de Azure Private Link entre Cloud Volumes ONTAP y sus cuentas de almacenamiento asociadas. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Descubra cómo Cloud Volumes ONTAP utiliza un enlace privado de Azure"^]

* Google Cloud
+
Para utilizar la consola y los servicios de datos con Google Cloud, implemente su agente en Google Cloud.

* En sus instalaciones




== Comunicación con proveedores de la nube

El agente utiliza TLS 1.3 para todas las comunicaciones con AWS, Azure y Google Cloud.



== Modo restringido

Para utilizar la consola en modo restringido, instale un agente de consola y acceda a la interfaz de la consola que se ejecuta localmente en el agente de consola.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de la NetApp Console"] .



== Cómo instalar un agente de consola

Puede instalar un agente de consola directamente desde la consola, desde el marketplace de su proveedor de nube o instalando manualmente el software en su propio host Linux o en su entorno VCenter.

* link:concept-modes.html["Obtenga más información sobre los modos de implementación de la NetApp Console"]
* link:task-quick-start-standard-mode.html["Comience a utilizar la NetApp Console en modo estándar"]
* link:task-quick-start-restricted-mode.html["Comience a usar la NetApp Console en modo restringido"]




== Permisos del proveedor de la nube

Necesita permisos específicos para crear el agente de consola directamente desde la NetApp Console y otro conjunto de permisos para el agente de consola en sí. Si crea el agente de consola en AWS o Azure directamente desde la consola, entonces la consola crea el agente de consola con los permisos que necesita.

Al utilizar la consola en modo estándar, la forma de proporcionar permisos depende de cómo planea crear el agente de la consola.

Para saber cómo configurar permisos, consulte lo siguiente:

* Modo estándar
+
** link:concept-install-options-aws.html["Opciones de instalación del agente en AWS"]
** link:concept-install-options-azure.html["Opciones de instalación del agente en Azure"]
** link:concept-install-options-google.html["Opciones de instalación del agente en Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Configurar permisos en la nube para implementaciones locales"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurar permisos para el modo restringido"]


Para ver los permisos exactos que el agente de la consola necesita para las operaciones diarias, consulte las siguientes páginas:

* link:reference-permissions-aws.html["Descubra cómo el agente de la consola utiliza los permisos de AWS"]
* link:reference-permissions-azure.html["Descubra cómo el agente de consola usa los permisos de Azure"]
* link:reference-permissions-gcp.html["Descubra cómo el agente de la consola utiliza los permisos de Google Cloud"]


Es su responsabilidad actualizar las políticas del agente de la consola a medida que se agreguen nuevos permisos en versiones posteriores.  Las notas de la versión enumeran nuevos permisos.



== Actualizaciones de agente

NetApp actualiza el software del agente mensualmente para agregar funciones y mejorar la estabilidad.  Algunas funciones de la consola, como Cloud Volumes ONTAP y la administración de clústeres ONTAP locales, dependen de la versión y la configuración del agente de la consola.

Cuando instala su agente en la nube, el agente de la consola se actualiza automáticamente si tiene acceso a Internet.



== Mantenimiento del sistema operativo y de máquinas virtuales

El mantenimiento del sistema operativo en el host del agente de la consola es responsabilidad suya (del cliente).  Por ejemplo, usted (el cliente) debe aplicar actualizaciones de seguridad al sistema operativo en el host del agente de la consola siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo.

Tenga en cuenta que usted (cliente) no necesita detener ningún servicio en el host de Console gent al aplicar actualizaciones de seguridad menores.

Si usted (cliente) necesita detener y luego iniciar la máquina virtual del agente de consola, debe hacerlo desde la consola de su proveedor de nube o mediante los procedimientos estándar para la administración local.

<<agents-must-be-operational-at-all-times,El agente de consola debe estar operativo en todo momento>> .



== Múltiples sistemas y agentes

Un agente puede administrar múltiples sistemas y soportar servicios de datos en la Consola.  Puede utilizar un solo agente para administrar varios sistemas según el tamaño de la implementación y los servicios de datos que utilice.

Para implementaciones a gran escala, trabaje con su representante de NetApp para dimensionar su entorno.  Comuníquese con el soporte de NetApp si experimenta problemas.

A continuación se muestran algunos ejemplos de implementaciones de agentes:

* Tienes un entorno multicloud (por ejemplo, AWS y Azure) y prefieres tener un agente en AWS y otro en Azure.  Cada uno administra los sistemas Cloud Volumes ONTAP que se ejecutan en esos entornos.
* Un proveedor de servicios puede utilizar una organización de consola para brindar servicios a sus clientes y, al mismo tiempo, utilizar otra organización para brindar recuperación ante desastres a una de sus unidades de negocios.  Cada organización necesita su propio agente.

