---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Un _agente de consola_ es un software de NetApp que se ejecuta en su red en la nube o en su red local.  Utilice un agente de consola para conectar los servicios de consola de NetApp a sus entornos de almacenamiento. 
---
= Obtenga más información sobre los agentes de la consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _agente de consola_ se ejecuta en su red en la nube o en su red local.  Utilice un agente de consola para conectar los servicios de consola de NetApp a sus entornos de almacenamiento.



== Qué puedes hacer sin un agente de consola

Algunas funciones y servicios de la consola están disponibles si no implementa un agente de consola:

* Amazon FSx for NetApp ONTAP
+
Algunas acciones requieren un agente de consola o un vínculo de cargas de trabajo de NetApp . https://docs.netapp.com/us-en/storage-management-fsx-ontap/start/concept-fsx-aws.html["Conozca qué acciones requieren un agente o enlace de consola"^]

* Centro de automatización
* Azure NetApp Files
+
No necesita un agente de consola para administrar Azure NetApp Files, pero se requiere uno para usar NetApp Data Classification para escanear Azure NetApp Files.

* Google Cloud NetApp Volumes
* Copia y sincronización de NetApp
* Asesor digital
* Supervisar el uso de la licencia, la supervisión de suscripciones requiere un agente de consola
+
Generalmente puedes agregar una licencia a la consola de NetApp sin un agente de consola.

+
Se requiere un agente para agregar licencias basadas en nodos de Cloud Volumes ONTAP porque los datos provienen de las licencias instaladas en los sistemas Cloud Volumes ONTAP .

* Descubrimiento directo de clústeres ONTAP locales
+
No necesita un agente de consola para agregar un clúster ONTAP local a la consola, pero se requiere uno para funciones y servicios de datos adicionales de la consola.

+
https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Obtenga más información sobre las opciones de descubrimiento y administración para clústeres ONTAP locales"^]

* Actualizaciones de software
* Sostenibilidad
* Cargas de trabajo de NetApp




== Cuando se requiere un agente de consola

En el modo estándar, la consola requiere un agente de consola para:

* Alertas
* Funciones de administración de Amazon FSx para ONTAP
* Almacenamiento de Amazon S3
* Almacenamiento de blobs de Azure
* Copia de seguridad y recuperación de NetApp
* Clasificación de datos
* Cloud Volumes ONTAP
* Recuperación ante desastres de NetApp
* Sistemas de la serie E
* Eficiencia económica ^1^
* Depósitos de Google Cloud Storage
* Integración del clúster ONTAP local con los servicios de datos de NetApp
* Resiliencia de NetApp frente al ransomware
* Sistemas StorageGRID
* Nivelación de la nube de NetApp
* Almacenamiento en caché de volumen de NetApp


^1^ Puede acceder a estos servicios sin un agente de consola, pero se requiere un agente de consola para iniciar acciones.

Siempre necesitas un agente de consola para usar la consola en modo restringido.



== Los agentes de consola deben estar operativos en todo momento

Los agentes de consola son una parte fundamental de la consola de NetApp .  Es su responsabilidad (la del cliente) asegurarse de que los agentes relevantes estén disponibles, operativos y accesibles en todo momento.  La consola puede manejar interrupciones breves del agente, pero debe solucionar las fallas de infraestructura rápidamente.

Esta documentación se rige por el EULA.  Utilizar el producto fuera de la documentación puede afectar su funcionalidad y sus derechos de EULA.



== Ubicaciones compatibles

Puede instalar agentes en las siguientes ubicaciones:

* Servicios web de Amazon
* Microsoft Azure
+
Implemente un agente de consola en Azure en la misma región que los sistemas Cloud Volumes ONTAP que administra. Alternativamente, impleméntelo en el https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiones de Azure"^] . Esto garantiza que se utilice una conexión de Azure Private Link entre Cloud Volumes ONTAP y sus cuentas de almacenamiento asociadas. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Descubra cómo Cloud Volumes ONTAP utiliza un enlace privado de Azure"^]

* Google Cloud
+
Para utilizar la consola y los servicios de datos con Google Cloud, implemente su agente en Google Cloud.

* En sus instalaciones




== Comunicación con proveedores de la nube

El agente utiliza TLS 1.3 para todas las comunicaciones con AWS, Azure y Google Cloud.



== Modo restringido

Para utilizar la consola en modo restringido, instale un agente de consola y acceda a la interfaz de la consola que se ejecuta localmente en el agente de consola.

link:concept-modes.html["Obtenga más información sobre los modos de implementación de la consola de NetApp"] .



== Cómo instalar un agente de consola

Puede instalar un agente de consola directamente desde la consola, desde el marketplace de su proveedor de nube o instalando manualmente el software en su propio host Linux o en su entorno VCenter.  La forma de comenzar dependerá de si utiliza la consola en modo estándar o en modo restringido.

* link:concept-modes.html["Obtenga más información sobre los modos de implementación de la consola de NetApp"]
* link:task-quick-start-standard-mode.html["Comience a utilizar la consola de NetApp en modo estándar"]
* link:task-quick-start-restricted-mode.html["Comience a usar la consola de NetApp en modo restringido"]




== Permisos en la nube

Necesita permisos específicos para crear el agente de consola directamente desde la consola de NetApp y otro conjunto de permisos para la instancia del agente de consola en sí.  Si crea el agente de consola en AWS o Azure directamente desde la consola, entonces la consola crea el agente de consola con los permisos que necesita.

Al utilizar la consola en modo estándar, la forma de proporcionar permisos depende de cómo planea crear el agente de la consola.

Para saber cómo configurar permisos, consulte lo siguiente:

* Modo estándar
+
** link:concept-install-options-aws.html["Opciones de instalación del agente en AWS"]
** link:concept-install-options-azure.html["Opciones de instalación del agente en Azure"]
** link:concept-install-options-google.html["Opciones de instalación del agente en Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Configurar permisos en la nube para implementaciones locales"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurar permisos para el modo restringido"]


Para ver los permisos exactos que el agente de la consola necesita para las operaciones diarias, consulte las siguientes páginas:

* link:reference-permissions-aws.html["Descubra cómo el agente de la consola utiliza los permisos de AWS"]
* link:reference-permissions-azure.html["Descubra cómo el agente de consola usa los permisos de Azure"]
* link:reference-permissions-gcp.html["Descubra cómo el agente de la consola utiliza los permisos de Google Cloud"]


Es su responsabilidad actualizar las políticas del agente de la consola a medida que se agreguen nuevos permisos en versiones posteriores.  Las notas de la versión enumeran nuevos permisos.



== Actualizaciones de agente

NetApp actualiza el software del agente mensualmente para agregar funciones y mejorar la estabilidad.  Algunas funciones de la consola, como Cloud Volumes ONTAP y la administración de clústeres de ONTAP locales, dependen de la versión y la configuración del agente de la consola.

En el modo estándar o restringido, el agente de la consola se actualiza automáticamente si tiene acceso a Internet.



== Mantenimiento del sistema operativo y de máquinas virtuales

El mantenimiento del sistema operativo en el host del agente de la consola es responsabilidad suya (del cliente).  Por ejemplo, usted (el cliente) debe aplicar actualizaciones de seguridad al sistema operativo en el host del agente de la consola siguiendo los procedimientos estándar de su empresa para la distribución del sistema operativo.

Tenga en cuenta que usted (cliente) no necesita detener ningún servicio en el host de Console gent al aplicar actualizaciones de seguridad menores.

Si usted (cliente) necesita detener y luego iniciar la máquina virtual del agente de consola, debe hacerlo desde la consola de su proveedor de nube o mediante los procedimientos estándar para la administración local.

<<agents-must-be-operational-at-all-times,El agente de consola debe estar operativo en todo momento>> .



== Múltiples sistemas y agentes

Un agente puede administrar múltiples sistemas y soportar servicios de datos en la Consola.  Puede utilizar un solo agente para administrar varios sistemas según el tamaño de la implementación y los servicios de datos que utilice.

Para implementaciones a gran escala, trabaje con su representante de NetApp para dimensionar su entorno.  Comuníquese con el soporte de NetApp si experimenta problemas.

A continuación se muestran algunos ejemplos de implementaciones de agentes:

* Tienes un entorno multicloud (por ejemplo, AWS y Azure) y prefieres tener un agente en AWS y otro en Azure.  Cada uno administra los sistemas Cloud Volumes ONTAP que se ejecutan en esos entornos.
* Un proveedor de servicios puede utilizar una organización de consola para brindar servicios a sus clientes y, al mismo tiempo, utilizar otra organización para brindar recuperación ante desastres a una de sus unidades de negocios.  Cada organización necesita su propio agente.

