---
sidebar: sidebar 
permalink: concept-install-options-azure.html 
keywords: install connector azure, azure install connector, connector azure, azure connector, installation options, azure marketplace, manual install 
summary: Hay algunas formas diferentes de crear un agente de consola en Azure.  La forma más común es hacerlo directamente desde la NetApp Console . 
---
= Opciones de instalación del agente de consola en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay algunas formas diferentes de crear un agente de consola en Azure.  La forma más común es hacerlo directamente desde la NetApp Console .

Están disponibles las siguientes opciones de instalación:

* link:task-install-agent-azure-console.html["Cree un agente de consola directamente desde la NetApp Console"](esta es la opción estándar)
+
Esta acción inicia una máquina virtual que ejecuta Linux y el software del agente de consola en una red virtual de su elección.

* link:task-install-agent-azure-marketplace.html["Crear un agente de consola desde Azure Marketplace"]
+
Esta acción también inicia una máquina virtual que ejecuta Linux y el software del agente de consola, pero la implementación se inicia directamente desde Azure Marketplace, en lugar de desde la consola.

* link:task-install-agent-azure-manual.html["Descargue e instale manualmente el software en su propio host Linux"]


La opción de instalación que elija afectará su forma de prepararse para la instalación.  Esto incluye cómo proporcionar al agente de consola los permisos necesarios para autenticar y administrar recursos en Azure.
