---
settings:
  name: NetApp Console setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Configuración y administración de la consola de NetApp
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Qué hay de nuevo
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/reference-limitations.html"
    - title: Cambios en los sistemas operativos Linux compatibles
      url: "/reference-agent-operating-system-changes.html"
  - title: Empezar
    entries:
    - title: Aprenda los conceptos básicos
      entries:
      - title: Consola de NetApp
        url: "/concept-overview.html"
      - title: Agentes de consola
        url: "/concept-agents.html"
      - title: Modos de implementación
        url: "/concept-modes.html"
    - title: Comience a utilizar el asistente de la consola de NetApp
      entries:
      - title: Utilice el asistente de la consola de NetApp
        url: "/task-console-assistant.html"
    - title: Comience con el modo estándar
      entries:
      - title: Flujo de trabajo de introducción
        url: "/task-quick-start-standard-mode.html"
      - title: Preparar el acceso a la red para la consola de NetApp
        url: "/reference-networking-saas-console.html"
      - title: Regístrese en la consola de NetApp
        url: "/task-sign-up-saas.html"
      - title: Crear un agente de consola
        entries:
        - title: AWS
          entries:
          - title: Opciones de instalación del agente de consola
            url: "/concept-install-options-aws.html"
          - title: Crear un agente de consola desde la consola de NetApp
            url: "/task-install-agent-aws-console.html"
          - title: Crear un agente de consola desde el mercado
            url: "/task-install-agent-aws-marketplace.html"
          - title: Instalar manualmente el agente de consola
            url: "/task-install-agent-aws-manual.html"
        - title: Azur
          entries:
          - title: Opciones de instalación del agente de consola
            url: "/concept-install-options-azure.html"
          - title: Crear un agente de consola desde la consola de NetApp
            url: "/task-install-agent-azure-console.html"
          - title: Crear un agente de consola desde el mercado
            url: "/task-install-agent-azure-marketplace.html"
          - title: Instalar manualmente el agente de consola
            url: "/task-install-agent-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opciones de instalación del agente de consola
            url: "/concept-install-options-google.html"
          - title: Crear un agente de consola desde la consola de NetApp
            url: "/task-install-agent-google-console-gcloud.html"
          - title: Crear un agente de consola desde Google Cloud
            url: "/task-install-agent-google-gcloud.html"
          - title: Instalar manualmente el agente de consola
            url: "/task-install-agent-google-manual.html"
        - title: Instalar un agente en las instalaciones
          entries:
          - title: Instalar manualmente un agente local
            url: "/task-install-agent-on-prem.html"
          - title: Instalar un agente local en VCenter
            url: "/task-install-agent-on-prem-ova.html"
      - title: Suscríbase a los servicios inteligentes de NetApp
        url: "/task-subscribe-standard-mode.html"
      - title: Qué puedes hacer a continuación
        url: "/reference-whats-next.html"
    - title: Comience con el modo restringido
      entries:
      - title: Flujo de trabajo de introducción
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepárese para el despliegue
        url: "/task-prepare-restricted-mode.html"
      - title: Implementar el agente de consola
        url: "/task-install-restricted-mode.html"
      - title: Suscríbase a los servicios inteligentes de NetApp
        url: "/task-subscribe-restricted-mode.html"
      - title: Qué puedes hacer a continuación
        url: "/reference-whats-next-restricted-mode.html"
    - title: Comience a usar la interfaz heredada de BlueXP (modo privado)
      entries:
      - title: Introducción a la interfaz heredada de BlueXP (modo privado)
        url: "/task-quick-start-private-mode.html"
  - title: Utilice la consola de NetApp
    entries:
    - title: Iniciar sesión en la consola de NetApp
      url: "/task-logging-in.html"
    - title: Ver métricas en la página de inicio de la consola de NetApp
      url: "/task-dashboard.html"
    - title: Administrar la configuración de usuario de la consola de NetApp
      url: "/task-user-settings.html"
  - title: Administrar la consola de NetApp
    entries:
    - title: Gestión de identidad y acceso
      entries:
      - title: Aprenda sobre la gestión de identidad y acceso
        url: "/concept-identity-and-access-management.html"
      - title: Comience con la identidad y el acceso
        url: "/task-iam-get-started.html"
      - title: Organiza tus recursos con carpetas y proyectos
        url: "/task-iam-manage-folders-projects.html"
      - title: Administrar miembros y cuentas de servicio
        url: "/task-iam-manage-members-permissions.html"
      - title: Utilice roles para controlar el acceso de los miembros a los recursos
        url: "/task-iam-manage-roles.html"
      - title: Gestione su jerarquía de recursos
        url: "/task-iam-manage-resources.html"
      - title: Asociar un agente de consola con otras carpetas y proyectos
        url: "/task-iam-associate-agents.html"
      - title: Cambiar entre organizaciones, proyectos y agentes de la consola
        url: "/task-iam-switch-organizations-projects.html"
      - title: Identificadores de organizaciones y proyectos
        url: "/task-iam-rename-organization.html"
      - title: Supervisar o auditar la actividad de IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Roles de acceso a la consola de NetApp
        entries:
        - title: Obtenga más información sobre los roles de acceso a la consola de
            NetApp
          url: "/reference-iam-predefined-roles.html"
        - title: Roles de la plataforma
          url: "/reference-iam-platform-roles.html"
        - title: Roles de aplicación
          entries:
          - title: Funciones de Google Cloud NetApp Volumes
            url: "/reference-iam-gcnv-roles.html"
          - title: Roles Keystone
            url: "/reference-iam-keystone-roles.html"
          - title: Analista de soporte de operaciones
            url: "/reference-iam-analyst-roles.html"
          - title: Roles de almacenamiento
            url: "/reference-iam-storage-roles.html"
        - title: Roles de servicios de datos
          entries:
          - title: Funciones de respaldo y recuperación
            url: "/reference-iam-backup-rec-roles.html"
          - title: Funciones de recuperación ante desastres
            url: "/reference-iam-disaster-rec-roles.html"
          - title: Funciones de protección contra ransomware
            url: "/reference-iam-ransomware-roles.html"
    - title: Organizaciones asociadas
      entries:
      - title: Conozca más sobre las asociaciones entre organizaciones
        url: "/concept-org-partnerships.html"
      - title: Crear una asociación organizacional
        url: "/task-partnerships-create.html"
      - title: Administrar miembros para una organización asociada
        url: "/task-partnerships-assign-users.html"
      - title: Administrar el acceso a los recursos para una organización asociada
        url: "/task-partnerships-resource-access.html"
      - title: Trabajar en una organización asociada
        url: "/task-partnerships-work.html"
    - title: Federación de identidades
      entries:
      - title: Obtenga más información sobre la federación de identidades
        url: "/concept-federation.html"
      - title: Verificación de dominio
        entries:
        - title: Verificar su dominio
          url: "/task-federation-verify-domain.html"
      - title: Configurar federaciones
        entries:
        - title: Federarse con un proveedor de Servicios de federación de Active Directory
            (AD FS)
          url: "/task-federation-adfs.html"
        - title: Federar con el proveedor de ID de Microsoft Entra
          url: "/task-federation-entra-id.html"
        - title: Federarse con PingFederate
          url: "/task-federation-ping.html"
        - title: Federarse con un proveedor de identidad SAML
          url: "/task-federation-saml.html"
      - title: Administrar federaciones
        url: "/task-federation-manage.html"
      - title: Importe su conexión federada existente
        url: "/task-federation-import.html"
    - title: Agentes de consola
      entries:
      - title: Mantener la máquina virtual y el sistema operativo
        url: "/task-maintain-agents.html"
      - title: Mantener un agente instalado en VCenter
        url: "/task-agent-vm-config.html"
      - title: Instalar un certificado firmado por una CA para acceder a la consola
          web
        url: "/task-installing-https-cert.html"
      - title: Configurar un agente de consola para utilizar un servidor proxy
        url: "/task-configuring-proxy.html"
      - title: Requerir el uso de IMDSv2 en instancias EC2
        url: "/task-require-imdsv2.html"
      - title: Administrar actualizaciones de agentes
        url: "/task-upgrade-agent.html"
      - title: Trabajar con múltiples agentes de consola
        url: "/task-manage-multiple-agents.html"
      - title: Solucionar problemas del agente de la consola
        url: "/task-troubleshoot-agent.html"
      - title: Desinstalar y eliminar el agente de consola
        url: "/task-uninstall-agent.html"
      - title: Configuración predeterminada
        url: "/reference-agent-default-config.html"
      - title: Aplicar permisos de ONTAP en la consola de NetApp
        url: "/task-ontap-access-agent.html"
    - title: Credenciales y suscripciones
      entries:
      - title: AWS
        entries:
        - title: Obtenga información sobre credenciales y permisos
          url: "/concept-accounts-aws.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-aws-accounts.html"
      - title: Azur
        entries:
        - title: Obtenga información sobre credenciales y permisos
          url: "/concept-accounts-azure.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Obtenga más información sobre proyectos y permisos
          url: "/concept-accounts-gcp.html"
        - title: Administrar credenciales y suscripciones
          url: "/task-adding-gcp-accounts.html"
      - title: Administrar las credenciales de NSS asociadas con una organización
          o cuenta de la consola de NetApp
        url: "/task-adding-nss-accounts.html"
      - title: Administrar las credenciales asociadas con el inicio de sesión de su
          consola de NetApp
        url: "/task-manage-user-credentials.html"
    - title: Supervisar las operaciones de la consola de NetApp
      url: "/task-monitor-cm-operations.html"
  - title: Referencia
    entries:
    - title: Consola de mantenimiento del agente
      entries:
      - title: Consola de mantenimiento del agente
        url: "/reference-agent-maint-console.html"
    - title: Permisos
      entries:
      - title: Resumen de permisos
        url: "/reference-permissions.html"
      - title: Permisos de AWS para el agente de consola
        url: "/reference-permissions-aws.html"
      - title: Permisos de Azure para el agente de consola
        url: "/reference-permissions-azure.html"
      - title: Permisos de Google Cloud para el agente de la consola
        url: "/reference-permissions-gcp.html"
    - title: Puertos
      entries:
      - title: Reglas del grupo de seguridad del agente de consola en AWS
        url: "/reference-ports-aws.html"
      - title: Reglas del grupo de seguridad del agente de consola en Azure
        url: "/reference-ports-azure.html"
      - title: Reglas de firewall del agente de consola en Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Puertos para el agente de consola local
        url: "/reference-ports-on-prem.html"
    - title: Acceso a la red de la consola (heredado)
      url: "/reference-networking-saas-console-previous.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
