---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: Debe asegurarse de que la consola y cualquier agente que instale tengan el acceso de red correcto para funcionar correctamente. 
---
= Acceso a la red requerido para 3.9.55 y anteriores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console, el agente de la NetApp Console y los servicios de datos de NetApp requieren acceso a Internet saliente para comunicarse con los puntos finales necesarios.


NOTE: Este tema documenta el acceso a la red necesario para las versiones del modo estándar de la NetApp Console 3.9.55 y anteriores.  Para conocer los puntos finales necesarios para 4.0.0 y superiores, reviselink:reference-networking-saas-console.html["los puntos finales necesarios para 4.0.0 y superiores"] .

Debe configurar el acceso a la red para lo siguiente:

* Computadoras que acceden a la NetApp Console como software como servicio (SaaS)
* Agentes de consola que se instalan localmente o en la nube.




== Actualice su lista de puntos finales a la lista revisada para 4.0.0 y versiones superiores

A partir de la versión 4.0.0, los agentes de consola requieren menos puntos finales.  Las implementaciones existentes anteriores a la versión 4.0.0 siguen siendo compatibles.  Después de actualizar a 4.0.0 o posterior, puede eliminar los puntos finales antiguos de su lista de permitidos cuando sea conveniente.

NetApp recomienda actualizar las reglas de firewall para utilizar la lista de puntos finales revisada, que es más pequeña, más segura y más fácil de administrar.  NetApp elimina la necesidad de entradas comodín y los puntos finales para actualizaciones de agentes admiten todos los servicios de datos.

[cols="3*"]
|===
| *Puntos finales para la versión 3.9.55 y anteriores* | *Puntos finales para 4.0.0 y superiores* | *Objetivo* 


 a| 
* \ https://support.netapp.com
* \ https://mysupport.netapp.com

 a| 
* \ https://mysupport.netapp.com
* \ https://signin.b2c.netapp.com
* \ https://support.netapp.com

 a| 
Para obtener licencias y comunicarse con el soporte técnico de NetApp .



 a| 
* \https://*.api.bluexp.netapp.com
* \ https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \ https://cloudmanager.cloud.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.bluexp.netapp.com
* \https://*.console.bluexp.netapp.com

 a| 
* \ https://api.bluexp.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \ https://components.console.bluexp.netapp.com
* \ https://cdn.auth0.com

 a| 
Para operaciones diarias.



 a| 
* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io

 a| 
* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io

| Para obtener imágenes para las actualizaciones del agente de consola. 
|===
.Pasos
. Verifique que su agente sea la versión 4.0.0 o superior.link:task-troubleshoot-agent.html#view-the-console-agent-version["Ver la versión del agente."]
. Incluir en la lista blanca los puntos finales enlink:reference-networking-saas-console.html["Puntos finales compatibles con 4.0.0 y superiores"] .
. Reinicie el servicio del administrador de servicios 2 en cada agente ejecutando el siguiente comando:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Ejecute el siguiente comando y verifique que el estado del agente se muestre como _activo(en ejecución)_: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. Elimina los puntos finales antiguos de la lista de permitidos de tu firewall.




== Puntos finales para la NetApp Console y los agentes de consola para la versión 3.9.55 y anteriores

Estos puntos finales se utilizan para agentes de consola 3.9.55 y anteriores.

[cols="2*"]
|===
| Puntos finales | Objetivo 


 a| 
\ https://support.netapp.com \ https://mysupport.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp .



 a| 
\https://\*.api.bluexp.netapp.com \ https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \ https://cloudmanager.cloud.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com
| Proporcionar funciones y servicios dentro de la NetApp Console. 


 a| 
Elija entre dos conjuntos de puntos finales:

* Opción 1 (recomendada)
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* Opción 2
+
\https://*.blob.core.windows.net\ https://cloudmanagerinfraprod.azurecr.io


 a| 
Para obtener imágenes para las actualizaciones del agente de consola.

NetApp recomienda permitir los puntos finales de la Opción 1 en su firewall, ya que son más seguros, y no permitir los puntos finales de la Opción 2, a menos que esté usando Ransomware Resilience o Backup and Recovery.  Tenga en cuenta lo siguiente acerca de estos puntos finales:

* Los puntos finales de la opción 1 son compatibles con 3.9.47 y versiones posteriores.  Las versiones anteriores a 3.9.47 no admiten compatibilidad con versiones anteriores.
* El agente de consola inicia primero el contacto con los puntos finales en la opción 2.  Si esos puntos finales no son accesibles, se contacta automáticamente con los puntos finales de la opción 1.
* Si utiliza el agente de consola con NetApp Backup and Recovery o Ransomware Resilience, el sistema no admite puntos finales de la Opción 1.  Permitir puntos finales de la Opción 2 y no permitir la Opción 1.


|===


== Puntos finales del proveedor de la nube contactados por el agente de la consola

Los agentes de consola deben tener acceso a puntos finales adicionales si están implementados en su proveedor de nube.

Habilite el acceso a los puntos finales del proveedor de nube antes de instalar el agente de consola.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurar el acceso a la red de AWS para un agente de consola"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurar el acceso a la red de Azure para un agente de consola"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurar el acceso a la red de Google Cloud para un agente de la consola"]


Los puntos finales del proveedor de nube son los mismos para todas las versiones.



== Puntos finales de servicios de datos contactados por el agente de la consola

El agente de consola requiere acceso a Internet saliente adicional para admitir algunos servicios de datos de NetApp y Cloud Volumes ONTAP.



=== Puntos finales para Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Puntos finales para Cloud Volumes ONTAP en AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Puntos de conexión para Cloud Volumes ONTAP en Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Puntos finales para Cloud Volumes ONTAP en Google Cloud"]

