---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: La NetApp Console, el agente de la NetApp Console y los servicios de datos de NetApp requieren acceso a Internet saliente y la capacidad de comunicarse con los puntos finales necesarios. 
---
= Preparar el acceso a la red para la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console, el agente de la NetApp Console y los servicios de datos de NetApp requieren acceso a Internet saliente y la capacidad de comunicarse con los puntos finales necesarios.

Necesitará configurar el acceso a la red para lo siguiente:

* Computadoras que acceden a la NetApp Console como software como servicio (SaaS)
* Ubicaciones de red donde implementa agentes de consola que instala localmente o en la nube.
* Puntos finales adicionales para ciertos servicios de datos de NetApp , incluido Cloud Volumes ONTAP.



NOTE: NetApp ha reducido los puntos finales de red necesarios para la consola y los agentes de consola, lo que mejora la seguridad y simplifica la implementación.  Es importante destacar que todas las implementaciones anteriores a la versión 4.0.0 continúan siendo totalmente compatibles.  Si bien los puntos finales anteriores siguen estando disponibles para los agentes existentes, NetApp recomienda encarecidamente actualizar las reglas de firewall para los puntos finales actuales después de confirmar que las actualizaciones de los agentes fueron exitosas.link:reference-networking-saas-console-previous.html["Aprenda cómo actualizar su lista de puntos finales."]



== Puntos finales contactados por la NetApp Console

Cada computadora que acceda a la NetApp Console debe tener conexiones a los puntos finales que se enumeran a continuación.

El sistema contacta estos puntos finales en dos escenarios:

* Desde una computadora accediendo al https://console.netapp.com["NetApp Console"^] como software como servicio (SaaS).
* Desde una computadora que accede directamente a un host del agente de la consola, ya sea para iniciar sesión y configurarlo o para acceder a la consola desde el host del agente.


[cols="2*"]
|===
| Puntos finales | Objetivo 


| \ https://mysupport.netapp.com | Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp . 


| \ https://signin.b2c.netapp.com | Para actualizar las credenciales del sitio de soporte de NetApp (NSS) o para agregar nuevas credenciales de NSS a la NetApp Console. 


| \ https://support.netapp.com | Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp , así como para recibir actualizaciones de software para Cloud Volumes ONTAP. 


| \ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com | Proporcionar funciones y servicios dentro de la NetApp Console. 


 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obtener imágenes para las actualizaciones del agente de consola.

* Cuando se implementa un nuevo agente, la verificación de validación prueba la conectividad con los puntos finales actuales. Si utilizaslink:reference-networking-saas-console-previous.html["puntos finales anteriores"] , la comprobación de validación falla. Para evitar este error, omita la comprobación de validación.
+
Aunque los puntos finales anteriores aún son compatibles, NetApp recomienda actualizar las reglas de firewall a los puntos finales actuales lo antes posible. link:reference-networking-saas-console-previous.html#update-endpoint-list["Aprenda a actualizar su lista de puntos finales"] .

* Cuando actualice los puntos finales actuales en su firewall, sus agentes existentes continuarán funcionando.


|===


== Preparar la red para el agente de consola

Instala el agente de la consola localmente o en la nube, y este se comunica con los puntos finales para completar las acciones iniciadas por la consola.

Los agentes de consola deben tener acceso a los mismos puntos finales que la NetApp Console, además de puntos finales adicionales según dónde instale el agente.

Configure el acceso al punto final de la red antes de instalar el agente de la consola.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurar el acceso a la red de AWS para un agente de consola"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurar el acceso a la red de Azure para un agente de consola"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurar el acceso a la red de Google Cloud para un agente de la consola"]
* link:task-install-agent-on-prem.html#network-access-agent["Configurar el acceso a la red local para un agente de consola"]




== Preparar la red para Cloud Volumes ONTAP

Algunos servicios de datos de NetApp , así como Cloud Volumes ONTAP, requieren que el agente tenga acceso a Internet saliente adicional.



=== Puntos finales para Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Puntos finales para Cloud Volumes ONTAP en AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Puntos de conexión para Cloud Volumes ONTAP en Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Puntos finales para Cloud Volumes ONTAP en Google Cloud"]


https://docs.netapp.com/us-en/data-services-family/["Consulte la documentación de los servicios de datos de NetApp correspondientes."^]
