---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions, bluexp, console agent 
summary: El agente de consola requiere permisos para realizar acciones en su proveedor de nube.  Estos permisos están incluidos en las políticas proporcionadas por NetApp.  Debes comprender qué hace el agente con estos permisos. 
---
= Permisos de Google Cloud para el agente de la consola
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El agente de la consola requiere permisos para realizar acciones en Google Cloud. Estos permisos están incluidos en una función personalizada proporcionada por NetApp. Debes comprender qué hace el agente con estos permisos.



== Permisos de la cuenta de usuario de Google Cloud

La siguiente función personalizada otorga a un usuario de Google Cloud los permisos necesarios para implementar un agente.  Aplique este rol personalizado al usuario que implementará el agente.

.Ver los permisos de la cuenta de usuario de Google Cloud
[%collapsible]
====
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
====


== Permisos de la cuenta de servicio

La función personalizada a continuación le otorga a la cuenta de servicio de Google Cloud asociada al agente de la consola los permisos necesarios para administrar recursos y procesos en su red de Google Cloud.

Aplique esta función personalizada a una cuenta de servicio asociada a la máquina virtual del agente de consola.

* link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Configurar los permisos de Google Cloud para el modo estándar"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurar permisos para el modo restringido"]


.Ver los permisos de la cuenta de servicio de Google
[%collapsible]
====
Asegúrese de que la función esté actualizada a medida que se agreguen o eliminen nuevos permisos en versiones posteriores.  El registro de cambios enumera todos los nuevos permisos necesarios.link:reference-permissions-gcp.html#gcp-permissions-change-log["Revisar el registro de cambios de permisos de Google"] link:task-adding-gcp-accounts.html["Revisa cómo agregar cuentas de servicio de Google Cloud"]

[source, yaml]
----
title: NetApp Console agent
description: Permissions for the service account associated with the Console agent.
stage: GA
includedPermissions:
- cloudbuild.builds.get
- cloudbuild.connections.list
- cloudbuild.repositories.accessReadToken
- cloudbuild.repositories.list
- cloudquotas.quotas.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
- config.artifacts.import
- config.deployments.create
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getLock
- config.deployments.getState
- config.deployments.update
- config.deployments.updateState
- config.previews.upload
- config.revisions.get
- config.revisions.getState
- config.deployments.getLock
- config.deployments.list
- config.deployments.lock
- config.operations.get
- config.previews.get
- config.previews.list
- config.resources.list
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.regionBackendServices.update
- compute.networks.updatePolicy
- compute.addresses.createInternal
- compute.addresses.deleteInternal
- compute.addresses.list
- compute.addresses.setLabels
- compute.addresses.useInternal
- compute.backendServices.create
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.forwardingRules.create
- compute.forwardingRules.delete
- compute.forwardingRules.get
- compute.forwardingRules.setLabels
- compute.globalOperations.get
- compute.healthChecks.create
- compute.healthChecks.delete
- compute.healthChecks.get
- compute.healthChecks.useReadOnly
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instances.use
- compute.instanceGroups.create
- compute.instanceGroups.delete
- compute.instanceGroups.get
- compute.instanceGroups.update
- compute.instanceGroups.use
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.instances.setMinCpuPlatform
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.regionBackendServices.delete
- compute.regionBackendServices.use
- compute.resourcePolicies.create
- compute.resourcePolicies.delete
- compute.resourcePolicies.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- logging.logEntries.create
- logging.logEntries.route
- monitoring.timeSeries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- storage.objects.create
- storage.objects.delete
- storage.objects.update
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.objects.get
- storage.buckets.getIamPolicy



----
====


== Cómo se utilizan los permisos de Google Cloud

El agente de la consola usa los permisos en la función personalizada para administrar los recursos de Cloud Volumes ONTAP y los procesos de servicios de datos de NetApp en su red de Google Cloud.  Las siguientes secciones describen cómo el agente utiliza estos permisos.



=== Permisos utilizados para Cloud Volumes ONTAP

El agente de la consola usa los permisos en la función personalizada para administrar los recursos y procesos de Cloud Volumes ONTAP en su red de Google Cloud.  Las siguientes secciones describen cómo el agente utiliza estos permisos.

.Permisos para Cloud Volumes ONTAP
[%collapsible]
====
[cols="5*"]
|===
| Comportamiento | Objetivo | ¿Se utiliza para implementación? | ¿Se utiliza para operaciones diarias? | ¿Se utiliza para eliminar? 


| config.deployments.create .15+| Para implementar la instancia de máquina virtual Cloud Volumes ONTAP mediante Google Cloud Infrastructure Manager. | Sí | No | No 


| config.deployments.delete | No | No | Sí 


| config.deployments.deleteState | No | No | Sí 


| config.deployments.get | No | Sí | No 


| config.deployments.getLock | No | Sí | No 


| config.deployments.getState | No | Sí | No 


| lista de configuraciones de despliegue | No | Sí | No 


| config.deployments.lock | No | Sí | No 


| config.deployments.update | No | Sí | No 


| config.deployments.updateState | No | Sí | No 


| config.operaciones.get | No | Sí | No 


| config.previews.get | No | Sí | No 


| lista de vistas previas de configuración | No | Sí | No 


| lista de recursos de configuración | No | Sí | No 


| config.revisions.get | No | Sí | No 


| crear.discos.computar .7+| Para crear y administrar discos para Cloud Volumes ONTAP. | Sí | Sí | No 


| compute.disks.createSnapshot | No | Sí | No 


| eliminar discos de cálculo | No | Sí | Sí 


| compute.disks.get | No | Sí | No 


| compute.disks.list | Sí | Sí | No 


| computar.discos.establecerEtiquetas | Sí | Sí | No 


| usar discos de cálculo | No | Sí | No 


| crear.cortafuegos. .4+| Para crear reglas de firewall para Cloud Volumes ONTAP. | Sí | No | No 


| compute.firewalls.delete | No | Sí | Sí 


| compute.firewalls.get | Sí | Sí | No 


| compute.firewalls.list | Sí | Sí | No 


| calcular.reenvíoReglas.crear | Cree reglas de reenvío para enrutar el tráfico hacia los servicios backend. | No | Sí | No 


| calcular.reenvíoReglas.eliminar | Eliminar reglas de reenvío existentes. | No | Sí | No 


| calcular.reenvíoReglas.obtener | Recupere detalles sobre las reglas de reenvío existentes. | No | Sí | No 


| calcular.reenvíoReglas.establecerEtiquetas | Establecer o actualizar etiquetas en las reglas de reenvío para la organización. | No | Sí | No 


| computar.globalOperations.get | Para obtener el estado de las operaciones. | Sí | Sí | No 


| computar.healthChecks.crear .4+| Cree y administre controles de estado para supervisar el estado del servicio backend. | No | Sí | No 


| computar.healthChecks.eliminar | No | Sí | No 


| computar.healthChecks.get | No | Sí | No 


| computar.healthChecks.useReadOnly | No | Sí | No 


| compute.images.get .4+| Para obtener imágenes para instancias de VM. | Sí | No | No 


| compute.images.getFromFamily | Sí | No | No 


| compute.images.list | Sí | No | No 


| compute.images.useReadOnly | Sí | No | No 


| compute.instances.attachDisk .2+| Para conectar y desconectar discos a Cloud Volumes ONTAP. | Sí | Sí | No 


| compute.instances.detachDisk | No | Sí | Sí 


| crear instancias de cómputo .2+| Para crear y eliminar instancias de VM de Cloud Volumes ONTAP . | Sí | No | No 


| compute.instances.delete | No | No | Sí 


| compute.instances.get | Para enumerar instancias de VM. | Sí | Sí | No 


| compute.instances.getSerialPortOutput | Para obtener registros de la consola. | Sí | Sí | No 


| compute.instances.list | Para recuperar la lista de instancias en una zona. | Sí | Sí | No 


| compute.instances.setDeletionProtection | Para establecer la protección contra eliminación en la instancia. | Sí | No | No 


| compute.instances.setLabels | Para agregar etiquetas. | Sí | No | No 


| compute.instances.setMachineType .2+| Para cambiar el tipo de máquina para Cloud Volumes ONTAP. | Sí | Sí | No 


| compute.instances.setMinCpuPlatform | Sí | Sí | No 


| compute.instances.setMetadata | Para agregar metadatos. | Sí | Sí | No 


| compute.instances.setTags | Para agregar etiquetas para las reglas de firewall. | Sí | Sí | No 


| compute.instances.start .3+| Para iniciar y detener Cloud Volumes ONTAP. | Sí | Sí | No 


| compute.instances.stop | Sí | Sí | No 


| compute.instances.updateDisplayDevice | Sí | Sí | No 


| computar.instancias.uso | Utilice instancias de máquinas virtuales (operaciones de inicio, detención y conexión). | No | Sí | No 


| compute.machineTypes.get | Para obtener el número de núcleos y comprobar las cuotas. | Sí | No | No 


| compute.projects.get | Para apoyar multiproyectos. | Sí | No | No 


| computar.políticasderecursos.crear .3+| Cree y administre políticas de recursos para la gestión automatizada de recursos. | No | Sí | No 


| computar.políticasderecursos.eliminar | No | Sí | No 


| computar.políticasderecursos.obtener | No | Sí | No 


| crear.instantáneas.computar .5+| Para crear y administrar instantáneas de disco persistentes. | Sí | Sí | No 


| compute.snapshots.delete | No | Sí | Sí 


| compute.snapshots.get | No | Sí | No 


| compute.snapshots.list | No | Sí | No 


| calcular.instantáneas.establecerEtiquetas | Sí | Sí | No 


| compute.networks.get .9+| Para obtener la información de red necesaria para crear una nueva instancia de máquina virtual Cloud Volumes ONTAP . | Sí | Sí | No 


| compute.networks.list | Sí | Sí | No 


| compute.regions.get | Sí | Sí | No 


| compute.regions.list | Sí | Sí | No 


| compute.subnetworks.get | Sí | Sí | No 


| compute.subnetworks.list | Sí | Sí | No 


| compute.zoneOperations.get | Sí | Sí | No 


| compute.zones.get | Sí | Sí | No 


| compute.zones.list | Sí | Sí | No 


| deploymentmanager.compositeTypes.get .16+| Para implementar la instancia de máquina virtual Cloud Volumes ONTAP mediante Google Cloud Deployment Manager. | Sí | No | No 


| deploymentmanager.compositeTypes.list | Sí | No | No 


| gestor de despliegue.despliegues.crear | Sí | No | No 


| gestor de despliegue.despliegues.eliminar | Sí | No | No 


| deploymentmanager.deployments.get | Sí | No | No 


| deploymentmanager.deployments.list | Sí | No | No 


| deploymentmanager.manifests.get | Sí | No | No 


| deploymentmanager.manifests.list | Sí | No | No 


| deploymentmanager.operations.get | Sí | No | No 


| lista de operaciones del administrador de despliegue | Sí | No | No 


| deploymentmanager.resources.get | Sí | No | No 


| deploymentmanager.resources.list | Sí | No | No 


| deploymentmanager.typeProviders.get | Sí | No | No 


| deploymentmanager.typeProviders.list | Sí | No | No 


| deploymentmanager.types.get | Sí | No | No 


| lista de tipos de gestor de despliegue | Sí | No | No 


| logging.logEntries.list .2+| Para obtener unidades de registro de pila. | Sí | Sí | No 


| logging.privateLogEntries.list | Sí | Sí | No 


| registro.logEntries.create .2+| Cree y enrute archivos de registro para monitoreo, depuración y auditoría. | Sí | Sí | No 


| registro.logEntries.route | Sí | Sí | No 


| resourcemanager.projects.get | Para apoyar multiproyectos. | Sí | Sí | No 


| almacenamiento.cubos.crear .5+| Para crear y administrar un depósito de Google Cloud Storage para la organización en niveles de datos. | Sí | Sí | No 


| almacenamiento.cubos.eliminar | No | Sí | Sí 


| almacenamiento.cubos.obtener | No | Sí | No 


| lista de cubos de almacenamiento | No | Sí | No 


| almacenamiento.cubos.actualizar | No | Sí | No 


| cloudkms.cryptoKeyVersions.useToEncrypt .5+| Para utilizar claves de cifrado administradas por el cliente desde el Servicio de administración de claves en la nube con Cloud Volumes ONTAP. | Sí | Sí | No 


| cloudkms.cryptoKeys.get | Sí | Sí | No 


| cloudkms.cryptoKeys.lista | Sí | Sí | No 


| lista de llaveros cloudkms | Sí | Sí | No 


| cloudbuild.builds.get | Sí | No | No 


| compute.instances.setServiceAccount .6+| Para configurar una cuenta de servicio en la instancia de Cloud Volumes ONTAP .  Esta cuenta de servicio proporciona permisos para la organización de datos en niveles en un depósito de Google Cloud Storage. | Sí | Sí | No 


| soy.cuentasdeservicio.actuar como | Sí | No | No 


| iam.serviceAccounts.create | Sí | No | No 


| iam.serviceAccounts.getIamPolicy | Sí | Sí | No 


| soy.serviceAccounts.list | Sí | Sí | No 


| iam.serviceAccountKeys.create | Sí | No | No 


| almacenamiento.objetos.crear .4+| Cree y administre objetos (archivos) en el depósito de Google Cloud Storage. | Sí | Sí | No 


| almacenamiento.objetos.eliminar | No | No | Sí 


| almacenamiento.objetos.obtener | Sí | Sí | No 


| almacenamiento.objetos.lista | Sí | Sí | No 


| calcular.direcciones.lista | Para recuperar las direcciones en una región al implementar un par HA. | Sí | No | No 


| computar.direcciones.crearInterno | Cree direcciones IP internas dentro de la red VPC para la asignación de recursos. | No | Sí | No 


| computar.direcciones.eliminarInterno | Eliminar direcciones IP internas para limpiar recursos. | No | Sí | No 


| calcular.direcciones.establecerEtiquetas | Actualizar etiquetas en el recurso Dirección. | No | Sí | No 


| computar.direcciones.useInternal | Utilice direcciones IP internas para la comunicación de red. | No | Sí | No 


| compute.backendServices.create | Configurar un servicio de backend para distribuir el tráfico en un par HA. | Sí | No | No 


| compute.regionBackendServices.create .6+| Crear y administrar servicios backend para enrutamiento de tráfico. | Sí | No | No 


| computar.regionBackendServices.eliminar | No | Sí | No 


| compute.regionBackendServices.get | Sí | No | No 


| computar.regionBackendServices.update | Sí | Sí | No 


| compute.regionBackendServices.list | Sí | No | No 


| computar.regiónBackendServices.uso | No | Sí | No 


| política de actualización de redes de computación | Para aplicar reglas de firewall en las VPC y subredes de un par de alta disponibilidad. | Sí | No | No 


| compute.instanceGroups.get .7+| Para crear y administrar máquinas virtuales de almacenamiento en pares HA de Cloud Volumes ONTAP . | Sí | Sí | No 


| calcular.direcciones.obtener | Sí | Sí | No 


| computar.instancias.actualizarInterfazDeRed | Sí | Sí | No 


| computar.gruposdeinstancias.crear | No | Sí | No 


| calcular.gruposdeinstancias.eliminar | No | Sí | No 


| computar.gruposdeinstancias.actualizar | No | Sí | No 


| computar.gruposdeinstancias.uso | No | Sí | No 


| monitorización.lista de series temporales .2+| Para descubrir información sobre los depósitos de Google Cloud Storage. | Sí | Sí | No 


| almacenamiento.cubos.obtenerPolíticaIam | Sí | Sí | No 
|===
====


=== Permisos utilizados para NetApp Backup and Recovery

El agente de consola usa los permisos en el rol personalizado para administrar los recursos y procesos de NetApp Backup and Recovery en su red de Google Cloud.  Las siguientes secciones describen cómo el agente utiliza estos permisos.

.Ver permisos para NetApp Backup and Recovery
[%collapsible]
====
[cols="5*"]
|===


| Comportamiento | Objetivo | ¿Se utiliza para implementación? | ¿Se utiliza para operaciones diarias? | ¿Se utiliza para eliminar? 


 a| 
* cloudkms.cryptoKeys.get
* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.lista
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* lista de llaveros cloudkms
* cloudkms.keyRings.setIamPolicy

| Para seleccionar sus propias claves administradas por el cliente en el asistente de activación de NetApp Backup and Recovery en lugar de utilizar las claves de cifrado administradas por Google predeterminadas. | Sí | Sí | No 
|===
====


=== Permisos utilizados para la NetApp Data Classification

El agente de consola usa los permisos en la función personalizada para administrar los recursos y procesos de NetApp Data Classification en su red de Google Cloud.  Las siguientes secciones describen cómo el agente utiliza estos permisos.

.Ver permisos para la NetApp Data Classification
[%collapsible]
====
[cols="5*"]
|===


| Comportamiento | Objetivo | ¿Se utiliza para implementación? | ¿Se utiliza para operaciones diarias? | ¿Se utiliza para eliminar? 


 a| 
* usar subredes de computación
* compute.subnetworks.useExternalIp
* compute.instances.addAccessConfig

| Para habilitar la NetApp Data Classification. | Sí | No | No 
|===
====


== Registro de cambios

Los permisos agregados y eliminados se detallan a continuación.



=== 08 de diciembre de 2025

NetApp está migrando de Google Cloud Deployment Manager a Google Cloud Infrastructure Manager (IM) para implementar y ejecutar el agente de consola en Google Cloud.  Se agregaron los siguientes permisos para respaldar este cambio.

Los siguientes permisos agregados son necesarios para el usuario de Google Cloud que implementa el agente:

* almacenamiento.cubos.crear
* almacenamiento.cubos.obtener
* almacenamiento.objetos.crear
* almacenamiento.carpetas.crear
* almacenamiento.objetos.lista
* iam.serviceAccount.actAs
* config.deployments.create
* config.operaciones.get


Se requieren los siguientes permisos adicionales para la cuenta de servicio en Google Cloud utilizada para las operaciones diarias:

* lista de conexiones de cloudbuild
* cloudbuild.repositories.accessReadToken
* lista de repositorios de cloudbuild
* cloudquotas.quotas.get
* config.artefactos.importar
* config.deployments.deleteState
* config.deployments.getLock
* config.deployments.getState
* config.deployments.updateState
* config.previews.upload
* config.revisions.getState
* registro.logEntries.create
* almacenamiento.objetos.crear
* almacenamiento.objetos.eliminar
* almacenamiento.objetos.actualizar
* iam.serviceAccounts.get


Se requieren los siguientes permisos agregados para implementar Cloud Volumes ONTAP:

* cloudbuild.builds.get
* config.deployments.delete
* config.deployments.deleteState
* config.deployments.get
* config.deployments.getState
* lista de configuraciones de despliegue
* config.deployments.update
* config.deployments.updateState
* config.previews.get
* lista de vistas previas de configuración
* config.revisions.get
* lista de recursos de configuración
* iam.serviceAccountKeys.create
* iam.serviceAccounts.create


Los siguientes permisos agregados son necesarios para la cuenta de servicio utilizada para las operaciones diarias de Cloud Volumes ONTAP.

* computar.direcciones.crearInterno
* computar.direcciones.eliminarInterno
* calcular.direcciones.establecerEtiquetas
* computar.direcciones.useInternal
* calcular.reenvíoReglas.crear
* calcular.reenvíoReglas.eliminar
* calcular.reenvíoReglas.obtener
* calcular.reenvíoReglas.establecerEtiquetas
* computar.healthChecks.crear
* computar.healthChecks.eliminar
* computar.healthChecks.get
* computar.healthChecks.useReadOnly
* computar.gruposdeinstancias.crear
* calcular.gruposdeinstancias.eliminar
* computar.gruposdeinstancias.actualizar
* computar.gruposdeinstancias.uso
* computar.instancias.uso
* computar.regionBackendServices.eliminar
* computar.regionBackendServices.update
* computar.regiónBackendServices.uso
* computar.políticasderecursos.crear
* computar.políticasderecursos.eliminar
* computar.políticasderecursos.obtener
* registro.logEntries.route
* config.deployments.create
* config.deployments.delete
* config.deployments.get
* config.deployments.update
* config.revisions.get
* config.deployments.lock
* config.operaciones.get




=== 26 de noviembre de 2025

Los permisos se han actualizado para aclarar su uso, pero no se han añadido ni eliminado permisos. Se añaden tres columnas para indicar si cada permiso se utiliza para la implementación, las operaciones diarias o la eliminación. Aparte de esto, algunos permisos están segregados en función de su uso para NetApp Data Classification y NetApp Backup and Recovery.



=== 6 de febrero de 2023

Se agregó el siguiente permiso a esta política:

* computar.instancias.actualizarInterfazDeRed


Este permiso es necesario para Cloud Volumes ONTAP.



=== 27 de enero de 2023

Se agregaron los siguientes permisos a esta política:

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.setIamPolicy


Estos permisos son necesarios para NetApp Backup and Recovery.
