---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: Puede utilizar la consola de mantenimiento del agente de consola para validar la instalación y configuración de un agente de consola. 
---
= Validación del agente de consola con la consola de mantenimiento en NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar la consola de mantenimiento del agente de consola para validar la instalación y configuración de un agente de consola.



== Acceder a la consola de mantenimiento del agente

Puedes acceder a la consola de mantenimiento desde el host del agente de consola. Navega hasta el siguiente directorio:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== Validación del comprobador de configuración

El `config-checker validate` El comando le permite validar la configuración de un agente de consola.



=== Parámetros

`--services <comma-separated list of services to validate>`--*REQUERIDO*--

[role="quick-margin-para"]
Elige uno o más servicios para validar. Los nombres de servicio válidos son:

* `PLATFORM` que valida la conectividad de red a los endpoints requeridos de la Console, así como si los puertos requeridos están abiertos para el agente de la Console.


`--validationTypes <comma-separated list of validation types to run>` --*REQUIRED*-- Elige uno o más tipos de validación para ejecutar. Los tipos de validación válidos son:

* `NETWORK` que valida la conectividad de red con los puntos finales de la NetApp Console requeridos.
* `HARDWARE` que valida que el host del agente cumple los requisitos mínimos de hardware para el agente de NetApp Console.
+

NOTE: Durante la instalación, NetApp comprueba que el host del agente tenga al menos el 80 por ciento del espacio en disco total disponible, lo que incluye 48 GB en `/opt` y 32 GB en `/var` (80 GB en total). Después de la instalación, requiere que al menos el 20 por ciento del disco total permanezca disponible, lo que incluye 12 GB en `/opt` y 8 GB en `/var` (20 GB en total).



`--proxy <url>`--*OPCIONAL*--

[role="quick-margin-para"]
Especifica la URL del servidor proxy que se utilizará para la validación.  Obligatorio si su agente está configurado para utilizar un servidor proxy.

`--certs <paths>`--*OPCIONAL*--

[role="quick-margin-para"]
Especifica la ruta a uno o más archivos de certificado que se utilizarán para la validación.  Los archivos del certificado deben estar en formato PEM.  Separe varias rutas con comas.  Este parámetro es necesario si su agente utiliza un certificado personalizado.



=== Ejemplos de validación del verificador de configuración

Los siguientes ejemplos incluyen la validación de la conectividad de red, los puertos necesarios y los requisitos de hardware junto con diferentes combinaciones de uso de un servidor proxy y certificados personalizados.

.Validación de la conectividad de red y los requisitos de hardware:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.Validación donde se utiliza un servidor proxy para el agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.Validación donde se utiliza un certificado para el agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== Ver ayuda para cualquier comando

Para ver la ayuda de cualquier comando, agregue `--help` al mando.  Por ejemplo, para ver la ayuda de la `proxy add` Comando, utilice el siguiente comando:

[source, cli]
----
./agent-maint-console proxy add --help
----