---
sidebar: sidebar 
permalink: reference-iam-data-classification.html 
keywords: role-based access control, IAM roles, access delegation, data classification, cloud data sense, compliance admin, classification viewer 
summary: NetApp Data Classification admite dos roles para gestionar el acceso de lectura y escritura a los activos. 
---
= NetApp roles de Data Classification en NetApp Console
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification es compatible con los roles de gestión de identidades y accesos (IAM), así puedes adaptar el acceso a las tareas que los usuarios necesitan realizar. Cómo asignes los roles depende de tu propia empresa y de tus prácticas de gestión del almacenamiento.

La clasificación de datos admite dos funciones:

* Administrador de cumplimiento
* Visor de clasificación




[[compliance-admin]]
== Administrador de cumplimiento

La función Compliance admin solo funciona a nivel de organización para gestionar el acceso a los recursos de NetApp Data Classification. Si un usuario tiene responsabilidades inferiores a las de un Organization admin, debe tener la función Compliance admin para instalar NetApp Data Classification.


IMPORTANT: El rol Compliance admin no es un rol independiente. Los usuarios con el rol Compliance admin también deben estar asociados con al menos un link:reference-iam-platform-roles.html["Rol de la plataforma"].


NOTE: La función de Compliance admin se añadió a NetApp Data Classification en la versión 1.54. Si habías implementado NetApp Data Classification antes de esta versión y tenías una función de plataforma con menos acceso que un organization admin, la función de Compliance admin se asoció automáticamente a la cuenta de usuario.



[[classification-viewer]]
== Visor de clasificación

El visor de clasificación está diseñado para usuarios que necesitan acceder a los resultados de los análisis en NetApp Data Classification, pero que no necesitan acceder a los recursos de configuración. Los usuarios con el rol de visor de clasificación pueden ver los resultados de la asignación y de los análisis completos para evaluar áreas donde se puede ahorrar espacio de almacenamiento o identificar posibles riesgos de datos. Los usuarios con el rol de visor de clasificación también pueden generar informes para los recursos a los que tienen acceso. Estos usuarios no pueden activar ni desactivar el análisis de volúmenes, buckets o esquemas de bases de datos.



[[more-information]]
== Más información

* link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["Conoce NetApp Data Classification"^]

