---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: Desinstala un agente de Console para solucionar problemas o para eliminarlo permanentemente del host. Los pasos que necesitas seguir dependen del modo de despliegue que estés usando. Una vez que hayas eliminado un agente de Console de tu entorno, puedes eliminarlo de la Console. 
---
= Desinstala y elimina un agente de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Desinstala un agente de Console para solucionar problemas o para eliminarlo permanentemente del host. Los pasos que necesitas seguir dependen del modo de despliegue que estés usando. Una vez que hayas eliminado un agente de Console de tu entorno, puedes eliminarlo de la Console.



[[uninstall-the-agent-when-it-has-outbound-connectivity]]
== Desinstala el agente cuando tiene conectividad de salida

Si está utilizando el modo estándar o el modo restringido (en otras palabras, el host del agente tiene conectividad saliente), debe seguir los pasos a continuación para desinstalar el agente.

.Pasos
. Conéctese a la máquina virtual Linux para el agente.
. Desde el host Linux, ejecute el script de desinstalación:
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ ejecuta el script sin solicitar confirmación.





[[uninstall-the-agent-when-it-has-no-outbound-connectivity]]
== Desinstala el agente cuando no tiene conectividad de salida

Si tu agente no tiene conectividad de salida (por ejemplo, en modo privado), debes eliminar manualmente el software del agente del host.

.Paso
. Conéctese a la máquina virtual Linux para el agente de consola.
. Desde el host Linux, ejecuta los siguientes comandos:
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Desde el host Linux, elimina los archivos de imagen de contenedor antiguos y no utilizados para liberar espacio libre en el directorio /var para la reinstalación.
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




[[remove-console-agents-from-the-console]]
== Eliminar agentes de la consola

Si ha eliminado una máquina virtual de agente o ha desinstalado el agente, debe eliminarlo de la lista de agentes en la consola. Después de eliminar una máquina virtual de agente o desinstalar el software del agente, este muestra el estado *Desconectado* en la consola.

Tenga en cuenta lo siguiente sobre la eliminación de un agente de consola:

* Esta acción no elimina la máquina virtual.
* Esta acción no se puede revertir: una vez que elimines un agente de consola, no podrás volver a agregarlo.


.Pasos
. Seleccione *Administración > Agentes*.
. En la página *Overview*, selecciona el menú de acciones para un agente desconectado y selecciona *Remove agent*.
. Ingrese el nombre del agente a confirmar y luego seleccione *Eliminar*.

