---
sidebar: sidebar 
permalink: task-federation-entra-id.html 
keywords: Microsoft Entra ID, BlueXP, federation, single sign-on, SSO, identity provider, IdP, service provider-initiated SSO, domain verification, client secret, redirect URL, organization admin, 
summary: 'Fedérese con su proveedor de IdP de Microsoft Entra ID para habilitar el inicio de sesión único (SSO) para la NetApp Console.  Esto permite a los usuarios iniciar sesión utilizando sus credenciales corporativas.' 
---
= Federar la NetApp Console con el ID de Microsoft Entra
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fedérese con su proveedor de IdP de Microsoft Entra ID para habilitar el inicio de sesión único (SSO) para la NetApp Console.  Esto permite a los usuarios iniciar sesión utilizando sus credenciales corporativas.

.Roles requeridos
El rol de administrador de la federación es necesario para crear y administrar federaciones.  El espectador de la Federación puede ver la página de la Federación.link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso."]


NOTE: Puede federarse con su IdP corporativo o con el sitio de soporte de NetApp .  NetApp recomienda elegir uno u otro, pero no ambos.

NetApp solo admite el inicio de sesión único (SSO) iniciado por el proveedor de servicios (SP).  Primero debe configurar el proveedor de identidad para confiar en NetApp como proveedor de servicios.  Luego, puede crear una conexión en la consola que utilice la configuración del proveedor de identidad.

Puede configurar una conexión federada con Microsoft Entra ID para habilitar el inicio de sesión único (SSO) para la consola.  El proceso implica configurar su ID de Microsoft Entra para confiar en la consola como proveedor de servicios y luego crear la conexión en la consola.

.Antes de empezar
* Se requiere una cuenta IdP con privilegios administrativos.  Coordínese con el administrador de su IdP para completar los pasos.
* Identifique el dominio que desea utilizar para la federación.  Puedes utilizar tu dominio de correo electrónico o un dominio diferente que sea de tu propiedad.  Si desea utilizar un dominio distinto a su dominio de correo electrónico, primero debe verificar el dominio en la Consola.  Puedes hacer esto siguiendo los pasos de lalink:task-federation-verify-domain.html["Verifique su dominio en la NetApp Console"] tema.


.Pasos
. Seleccione *Administración > Identidad y acceso*.
. Seleccione *Federación* para ver la página *Federaciones*.
. Seleccione *Configurar nueva federación*.


[discrete]
====== Detalles del dominio

. Introduzca los detalles de su dominio:
+
.. Elija si desea utilizar un dominio verificado o su dominio de correo electrónico.  El dominio de correo electrónico es el dominio asociado con la cuenta con la que ha iniciado sesión.
.. Introduzca el nombre de la federación que está configurando.
.. Si elige un dominio verificado, seleccione el dominio de la lista.


. Seleccione *Siguiente*.


[discrete]
====== Método de conexión

. Para su método de conexión, elija *Proveedor* y luego seleccione *Microsoft Entra ID*.
. Seleccione *Siguiente*.


[discrete]
====== Instrucciones de configuración

. Configure su ID de Microsoft Entra para confiar en NetApp como proveedor de servicios.  Debe realizar este paso en su servidor Microsoft Entra ID.
+
.. Utilice los siguientes valores al registrar su aplicación Microsoft Entra ID para confiar en la consola:
+
*** Para la *URL de redirección*, utilice `https://services.cloud.netapp.com`
*** Para la *URL de respuesta*, utilice `https://netapp-cloud-account.auth0.com/login/callback`


.. Cree un secreto de cliente para su aplicación Microsoft Entra ID.  Necesitará proporcionar el ID del cliente, el secreto del cliente y el nombre de dominio de Entra ID para completar la federación.


. Regrese a la consola y seleccione *Siguiente* para crear la conexión.


[discrete]
====== Crear conexión

. Crear la conexión con Microsoft Entra ID
+
.. Ingrese el ID de cliente y el secreto de cliente que creó en el paso anterior.
.. Introduzca el nombre de dominio de Microsoft Entra ID.


. Seleccione *Crear conexión*.  El sistema crea la conexión en unos segundos.


[discrete]
====== Probar y habilitar la conexión

. Seleccione *Siguiente*.
. Seleccione *Probar conexión* para probar su conexión.  Se le dirigirá a una página de inicio de sesión para su servidor IdP.  Inicie sesión con sus credenciales de IdP para completar la prueba y regresar a la consola para habilitar la conexión.
. Seleccione *Siguiente*.
. En la página *Habilitar federación*, revise los detalles de la federación y luego seleccione *Habilitar federación*.
. Seleccione *Finalizar* para completar el proceso.


Después de habilitar la federación, los usuarios pueden iniciar sesión en la NetApp Console con sus credenciales corporativas.
