---
sidebar: sidebar 
permalink: task-install-agent-google-console-gcloud.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, create connector, gcp installation, gcp connector 
summary: Para crear un agente de consola en Google Cloud desde NetApp Consoel o mediante Google Cloud, debe configurar su red, preparar los permisos de Google Cloud, habilitar las API de Google Cloud y, luego, crear el agente de consola. 
---
= Crear un agente de consola en Google Cloud desde la consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puedes crear un agente de consola en Google Cloud desde la consola.  Debe configurar su red, preparar los permisos de Google Cloud, habilitar las API de Google Cloud y luego crear el agente de consola.

.Antes de empezar
* Deberías tener unalink:concept-agents.html["comprensión de los agentes de consola"] .
* Deberías revisarlink:reference-limitations.html["Limitaciones del agente de consola"] .




== Paso 1: Configurar la red

Configure la red para garantizar que el agente de la consola pueda administrar recursos, con conexiones a redes de destino y acceso a Internet saliente.

VPC y subred:: Cuando crea el agente de consola, debe especificar la VPC y la subred donde debe residir.


Conexiones a redes de destino:: El agente de consola requiere una conexión de red a la ubicación donde planea crear y administrar sistemas.  Por ejemplo, la red donde planea crear sistemas Cloud Volumes ONTAP o un sistema de almacenamiento en su entorno local.


Acceso a Internet de salida:: La ubicación de red donde implementa el agente de consola debe tener una conexión a Internet saliente para comunicarse con puntos finales específicos.


Puntos finales contactados desde el agente de la consola:: El agente de la consola requiere acceso a Internet saliente para comunicarse con los siguientes puntos finales para administrar recursos y procesos dentro de su entorno de nube pública para las operaciones diarias.
+
--
Los puntos finales enumerados a continuación son todas entradas CNAME.

[cols="2a,1a"]
|===
| Puntos finales | Objetivo 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Para administrar recursos en Google Cloud.



 a| 
\ https://mysupport.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp .



 a| 
\ https://support.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp .



 a| 
\ https://signin.b2c.netapp.com
 a| 
Para actualizar las credenciales del sitio de soporte de NetApp (NSS) o para agregar nuevas credenciales de NSS a la consola de NetApp .



 a| 
\https:\\support.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp , así como para recibir actualizaciones de software para Cloud Volumes ONTAP.



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
Proporcionar funciones y servicios dentro de la consola de NetApp .



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obtener imágenes para las actualizaciones del agente de consola.

* Cuando se implementa un nuevo agente, la verificación de validación prueba la conectividad con los puntos finales actuales.  Si utilizaslink:link:reference-networking-saas-console-previous.html["puntos finales anteriores"] , la comprobación de validación falla.  Para evitar este error, omita la comprobación de validación.
+
Aunque los puntos finales anteriores aún son compatibles, NetApp recomienda actualizar las reglas de firewall a los puntos finales actuales lo antes posible. link:reference-networking-saas-console-previous.html#update-endpoint-list["Aprenda a actualizar su lista de puntos finales"] .

* Cuando actualice los puntos finales actuales en su firewall, sus agentes existentes continuarán funcionando.


|===
--


Puntos finales contactados desde la consola de NetApp:: A medida que utiliza la consola NetApp basada en web que se proporciona a través de la capa SaaS, esta se comunica con varios puntos finales para completar tareas de administración de datos.  Esto incluye los puntos finales que se contactan para implementar el agente de la consola desde la consola.
+
--
link:reference-networking-saas-console.html["Ver la lista de puntos finales contactados desde la consola de NetApp"] .

--


Servidor proxy:: NetApp admite configuraciones de proxy explícitas y transparentes.  Si está utilizando un proxy transparente, solo necesita proporcionar el certificado para el servidor proxy.  Si está utilizando un proxy explícito, también necesitará la dirección IP y las credenciales.
+
--
* Dirección IP
* Cartas credenciales
* Certificado HTTPS


--


Puertos:: No hay tráfico entrante al agente de la consola, a menos que usted lo inicie o si se utiliza como proxy para enviar mensajes de AutoSupport desde Cloud Volumes ONTAP al soporte de NetApp .
+
--
* HTTP (80) y HTTPS (443) brindan acceso a la interfaz de usuario local, que utilizará en circunstancias excepcionales.
* SSH (22) solo es necesario si necesita conectarse al host para solucionar problemas.
* Se requieren conexiones entrantes a través del puerto 3128 si implementa sistemas Cloud Volumes ONTAP en una subred donde no hay una conexión a Internet saliente disponible.
+
Si los sistemas Cloud Volumes ONTAP no tienen una conexión a Internet saliente para enviar mensajes de AutoSupport , la consola configura automáticamente esos sistemas para usar un servidor proxy que está incluido con el agente de la consola.  El único requisito es garantizar que el grupo de seguridad del agente de la consola permita conexiones entrantes a través del puerto 3128.  Necesitará abrir este puerto después de implementar el agente de consola.



--


Habilitar NTP:: Si planea utilizar NetApp Data Classification para escanear sus fuentes de datos corporativos, debe habilitar un servicio de Protocolo de tiempo de red (NTP) tanto en el agente de consola como en el sistema de clasificación de datos de NetApp para que la hora se sincronice entre los sistemas. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Obtenga más información sobre la clasificación de datos de NetApp"^]
+
--
Implemente este requisito de red después de crear el agente de consola.

--




== Paso 2: Configurar permisos para crear el agente de consola

Antes de poder implementar un agente de consola desde la consola, debe configurar permisos para el usuario de Google Platform que implementa la máquina virtual del agente de consola.

.Pasos
. Crear un rol personalizado en Google Platform:
+
.. Cree un archivo YAML que incluya los siguientes permisos:
+
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. Desde Google Cloud, activa Cloud Shell.
.. Sube el archivo YAML que incluye los permisos necesarios.
.. Cree un rol personalizado mediante el uso de `gcloud iam roles create` dominio.
+
El siguiente ejemplo crea un rol denominado "connectorDeployment" a nivel de proyecto:

+
Roles de iam de gcloud crean un conectorDeployment --project=myproject --file=connector-deployment.yaml

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentación de Google Cloud: Creación y administración de roles personalizados"^]



. Asigne este rol personalizado al usuario que implementará el agente de la consola desde la consola o mediante gcloud.
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentación de Google Cloud: Otorgar una función única"^]





== Paso 3: Configurar permisos para las operaciones del agente de la consola

Se requiere una cuenta de servicio de Google Cloud para proporcionar al agente de la consola los permisos que necesita para administrar recursos en Google Cloud.  Cuando cree el agente de consola, deberá asociar esta cuenta de servicio con la máquina virtual del agente de consola.

Es su responsabilidad actualizar la función personalizada a medida que se agreguen nuevos permisos en versiones posteriores.  Si se requieren nuevos permisos, se enumerarán en las notas de la versión.

.Pasos
. Crear un rol personalizado en Google Cloud:
+
.. Cree un archivo YAML que incluya el contenido delink:reference-permissions-gcp.html["Permisos de cuenta de servicio para el agente de consola"] .
.. Desde Google Cloud, activa Cloud Shell.
.. Sube el archivo YAML que incluye los permisos necesarios.
.. Cree un rol personalizado mediante el uso de `gcloud iam roles create` dominio.
+
El siguiente ejemplo crea un rol denominado "conector" a nivel de proyecto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentación de Google Cloud: Creación y administración de roles personalizados"^]



. Cree una cuenta de servicio en Google Cloud y asígnele el rol:
+
.. Desde el servicio IAM y administración, seleccione *Cuentas de servicio > Crear cuenta de servicio*.
.. Ingrese los detalles de la cuenta de servicio y seleccione *Crear y continuar*.
.. Seleccione el rol que acaba de crear.
.. Complete los pasos restantes para crear el rol.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentación de Google Cloud: Creación de una cuenta de servicio"^]



. Si planea implementar sistemas Cloud Volumes ONTAP en proyectos diferentes al proyecto donde reside el agente de la consola, deberá proporcionar a la cuenta de servicio del agente de la consola acceso a esos proyectos.
+
Por ejemplo, supongamos que el agente de consola está en el proyecto 1 y desea crear sistemas Cloud Volumes ONTAP en el proyecto 2.  Necesitará otorgar acceso a la cuenta de servicio en el proyecto 2.

+
.. Desde el servicio IAM y administración, seleccione el proyecto de Google Cloud donde desea crear sistemas Cloud Volumes ONTAP .
.. En la página *IAM*, seleccione *Otorgar acceso* y proporcione los detalles requeridos.
+
*** Ingrese el correo electrónico de la cuenta de servicio del agente de la consola.
*** Seleccione el rol personalizado del agente de consola.
*** Seleccione *Guardar*.




+
Para más detalles, consulte https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentación de Google Cloud"^]





== Paso 4: Configurar permisos de VPC compartidos

Si está utilizando una VPC compartida para implementar recursos en un proyecto de servicio, deberá preparar sus permisos.

Esta tabla es de referencia y su entorno debe reflejar la tabla de permisos cuando se complete la configuración de IAM.

.Ver permisos de VPC compartidos
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidad | Creador | Alojado en | Permisos del proyecto de servicio | Permisos del proyecto anfitrión | Objetivo 


| Cuenta de Google para implementar el agente | Costumbre | Proyecto de servicio  a| 
link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Política de implementación del agente"]
 a| 
computar.usuariodered
| Implementación del agente en el proyecto de servicio 


| cuenta de servicio del agente | Costumbre | Proyecto de servicio  a| 
link:reference-permissions-gcp.html["Política de cuenta de servicio del agente"]
| Compute.NetworkUser administrador de implementación.editor | Implementación y mantenimiento de Cloud Volumes ONTAP y los servicios en el proyecto de servicio 


| Cuenta de servicio de Cloud Volumes ONTAP | Costumbre | Proyecto de servicio | Miembro de storage.admin: cuenta de servicio de la consola de NetApp como serviceAccount.user | N/A | (Opcional) Para NetApp Cloud Tiering y NetApp Backup and Recovery 


| Agente de servicio de las API de Google | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Interactúa con las API de Google Cloud en nombre de la implementación.  Permite que la consola utilice la red compartida. 


| Cuenta de servicio predeterminada de Google Compute Engine | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Implementa instancias de Google Cloud y la infraestructura computacional en nombre de la implementación.  Permite que la consola utilice la red compartida. 
|===
Notas:

. deploymentmanager.editor solo es necesario en el proyecto host si no pasa reglas de firewall a la implementación y elige dejar que la consola las cree por usted.  La consola de NetApp crea una implementación en el proyecto de host que contiene la regla de firewall VPC0 si no se especifica ninguna regla.
. firewall.create y firewall.delete solo son necesarios si no pasa reglas de firewall a la implementación y elige dejar que la Consola las cree por usted.  Estos permisos residen en el archivo .yaml de la cuenta de la consola.  Si está implementando un par HA mediante una VPC compartida, estos permisos se utilizarán para crear las reglas de firewall para VPC1, 2 y 3.  Para todas las demás implementaciones, estos permisos también se utilizarán para crear reglas para VPC0.
. Para la organización en niveles de nube, la cuenta de servicio de organización en niveles debe tener el rol serviceAccount.user en la cuenta de servicio, no solo en el nivel de proyecto.  Actualmente, si asigna serviceAccount.user en el nivel del proyecto, los permisos no se muestran cuando consulta la cuenta de servicio con getIAMPolicy.


====


== Paso 5: Habilitar las API de Google Cloud

Debe habilitar varias API de Google Cloud antes de implementar el agente de consola y Cloud Volumes ONTAP.

.Paso
. Habilite las siguientes API de Google Cloud en su proyecto:
+
** API de Cloud Deployment Manager V2
** API de registro en la nube
** API del administrador de recursos en la nube
** API de Compute Engine
** API de gestión de identidad y acceso (IAM)
** API del servicio de administración de claves en la nube (KMS)
+
(Obligatorio solo si planea utilizar NetApp Backup and Recovery con claves de cifrado administradas por el cliente (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentación de Google Cloud: Habilitación de API"^]



== Paso 6: Crear el agente de consola

Cree un agente de consola directamente desde la consola.

.Acerca de esta tarea
Al crear el agente de consola, se implementa una instancia de máquina virtual en Google Cloud utilizando una configuración predeterminada. No cambie a una instancia de VM más pequeña con menos CPU o menos RAM después de crear el agente de consola. link:reference-agent-default-config.html["Obtenga información sobre la configuración predeterminada para el agente de la consola"] .

.Antes de empezar
Debes tener lo siguiente:

* Los permisos de Google Cloud necesarios para crear el agente de consola y una cuenta de servicio para la máquina virtual del agente de consola.
* Una VPC y una subred que cumple con los requisitos de red.
* Detalles sobre un servidor proxy, si se requiere un proxy para el acceso a Internet desde el agente de la consola.


.Pasos
. Seleccione *Administración > Agentes*.
. En la página *Descripción general*, seleccione *Implementar agente > Google Cloud*
. En la página *Implementación de un agente*, revise los detalles sobre lo que necesitará.  Tienes dos opciones:
+
.. Seleccione *Continuar* para prepararse para la implementación utilizando la guía del producto.  Cada paso de la guía del producto incluye la información contenida en esta página de la documentación.
.. Seleccione *Ir a implementación* si ya se preparó siguiendo los pasos de esta página.


. Siga los pasos del asistente para crear el agente de consola:
+
** Si se le solicita, inicie sesión en su cuenta de Google, que debería tener los permisos necesarios para crear la instancia de máquina virtual.
+
El formulario es propiedad de Google y está alojado por esta empresa.  Sus credenciales no se proporcionan a NetApp.

** *Detalles*: Ingrese un nombre para la instancia de la máquina virtual, especifique las etiquetas, seleccione un proyecto y luego seleccione la cuenta de servicio que tenga los permisos necesarios (consulte la sección anterior para obtener más detalles).
** *Ubicación*: especifique una región, zona, VPC y subred para la instancia.
** *Red*: elija si desea habilitar una dirección IP pública y, opcionalmente, especificar una configuración de proxy.
** *Etiquetas de red*: agregue una etiqueta de red a la instancia del agente de consola si usa un proxy transparente.  Las etiquetas de red deben comenzar con una letra minúscula y pueden contener letras minúsculas, números y guiones.  Las etiquetas deben terminar con una letra minúscula o un número.  Por ejemplo, puede utilizar la etiqueta "console-agent-proxy".
** *Política de firewall*: elija si desea crear una nueva política de firewall o si desea seleccionar una política de firewall existente que permita las reglas de entrada y salida requeridas.
+
link:reference-ports-gcp.html["Reglas de firewall en Google Cloud"]



. Revise sus selecciones para verificar que su configuración sea correcta.
+
.. La casilla de verificación *Validar configuración del agente* está marcada de forma predeterminada para que la consola valide los requisitos de conectividad de red cuando se implementa.  Si la consola no logra implementar el agente, proporciona un informe para ayudarlo a solucionar el problema.  Si la implementación se realiza correctamente, no se proporciona ningún informe.


+
[]
====
Si todavía estás usando ellink:reference-networking-saas-console-previous.html["puntos finales anteriores"] utilizado para actualizaciones de agente, la validación falla con un error.  Para evitar esto, desmarque la casilla de verificación para omitir la comprobación de validación.

====
. Seleccione *Agregar*.
+
La instancia estará lista en aproximadamente 10 minutos; permanezca en la página hasta que se complete el proceso.



.Resultado
Una vez completado el proceso, el agente de consola estará disponible para su uso.


NOTE: Si la implementación falla, puedes descargar un informe y registros desde la Consola para ayudarte a solucionar los problemas.link:task-troubleshoot-agent.html#troubleshoot-installation["Aprenda a solucionar problemas de instalación."]

Si tiene depósitos de Google Cloud Storage en la misma cuenta de Google Cloud donde creó el agente de consola, verá aparecer automáticamente un sistema de Google Cloud Storage en la página *Sistemas*. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["Aprenda a administrar Google Cloud Storage desde la consola"]
