---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: Para instalar manualmente el agente de la consola en su propio host Linux, debe revisar los requisitos del host, configurar su red, preparar los permisos de Google Cloud, habilitar las API de Google Cloud, instalar la consola y luego proporcionar los permisos que preparó. 
---
= Instalar manualmente el agente de la consola en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para instalar manualmente el agente de la consola en su propio host Linux, debe revisar los requisitos del host, configurar su red, preparar los permisos de Google Cloud, habilitar las API de Google Cloud, instalar la consola y luego proporcionar los permisos que preparó.

.Antes de empezar
* Deberías tener unalink:concept-connectors.html["comprensión de los agentes de consola"] .
* Deberías revisarlink:reference-limitations.html["Limitaciones del agente de consola"] .




== Paso 1: Revisar los requisitos del host

El software del agente de consola debe ejecutarse en un host que cumpla con los requisitos específicos del sistema operativo, requisitos de RAM, requisitos de puerto, etc.


NOTE: El agente de consola reserva el rango de UID y GID de 19000 a 19200.  Este rango es fijo y no se puede modificar.  Si algún software de terceros en su host utiliza UID o GID dentro de este rango, la instalación del agente fallará.  NetApp recomienda utilizar un host que esté libre de software de terceros para evitar conflictos.

Host dedicado:: El agente de consola no es compatible con un host compartido con otras aplicaciones. El host debe ser un host dedicado.  El host puede ser de cualquier arquitectura que cumpla con los siguientes requisitos de tamaño:
+
--
* CPU: 8 núcleos u 8 vCPU
* RAM: 32 GB
* Espacio en disco: se recomiendan 165 GB para el host, con los siguientes requisitos de partición:
+
** `/opt`:Debe haber 120 GiB de espacio disponibles
+
El agente utiliza `/opt` Para instalar el `/opt/application/netapp` directorio y su contenido.

** `/var`:Debe haber 40 GiB de espacio disponibles
+
El agente de consola requiere este espacio en `/var` porque Docker o Podman están diseñados para crear los contenedores dentro de este directorio.  En concreto, crearán contenedores en el `/var/lib/containers/storage` directorio.  Los montajes externos o enlaces simbólicos no funcionan para este espacio.





--
Hipervisor:: Se requiere un hipervisor alojado o de metal desnudo que esté certificado para ejecutar un sistema operativo compatible.
[[podman-versions]]Requisitos del sistema operativo y del contenedor:: El agente de consola es compatible con los siguientes sistemas operativos cuando se utiliza la consola en modo estándar o modo restringido.  Se requiere una herramienta de orquestación de contenedores antes de instalar el agente.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| Sistema operativo | Versiones de sistema operativo compatibles | Versiones de agente compatibles | Herramienta de contenedor requerida | SELinux a 


 a| 
Red Hat Enterprise Linux
 a| 
9.1 a 9.4

8.6 a 8.10

* Sólo versiones en idioma inglés.
* El host debe estar registrado en Red Hat Subscription Management.  Si no está registrado, el host no puede acceder a los repositorios para actualizar el software de terceros requerido durante la instalación del agente.

 a| 
3.9.50 o posterior con la consola en modo estándar o modo restringido
 a| 
Versión de Podman 4.6.1 o 4.9.4

<<podman-configuration,Ver los requisitos de configuración de Podman>> .
 a| 
Compatible con modo de aplicación o modo permisivo

* La administración de los sistemas Cloud Volumes ONTAP NO es compatible con agentes que tengan SELinux habilitado en el sistema operativo.




 a| 
Ubuntu
 a| 
24,04 LTS
 a| 
3.9.45 o posterior con la consola de NetApp en modo estándar o modo restringido
 a| 
Motor Docker 23.06 a 28.0.0.
 a| 
No compatible



 a| 
22,04 LTS
 a| 
3.9.50 o posterior
 a| 
Motor Docker 23.0.6 a 28.0.0.
 a| 
No compatible

|===
--
Tipo de máquina de Google Cloud:: Un tipo de instancia que cumple con los requisitos de CPU y RAM anteriores.  Recomendamos n2-standard-8.
+
--
El agente de consola es compatible con Google Cloud en una instancia de máquina virtual con un sistema operativo compatible. https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Características de las máquinas virtuales protegidas"^]

--
Espacio en disco en /opt:: Deben estar disponibles 100 GiB de espacio
+
--
El agente utiliza `/opt` Para instalar el `/opt/application/netapp` directorio y su contenido.

--
Espacio en disco en /var:: Deben estar disponibles 20 GiB de espacio
+
--
El agente de consola requiere este espacio en `/var` porque Docker o Podman están diseñados para crear los contenedores dentro de este directorio.  En concreto, crearán contenedores en el `/var/lib/containers/storage` directorio.  Los montajes externos o enlaces simbólicos no funcionan para este espacio.

--




== Paso 2: Instalar Podman o Docker Engine

Dependiendo de su sistema operativo, se requiere Podman o Docker Engine antes de instalar el agente.

* Podman es necesario para Red Hat Enterprise Linux 8 y 9.
+
<<podman-versions,Ver las versiones compatibles de Podman>> .

* Se requiere Docker Engine para Ubuntu.
+
<<podman-versions,Ver las versiones compatibles de Docker Engine>> .



.Pasos
[role="tabbed-block"]
====
.Podman
--
Siga estos pasos para instalar y configurar Podman:

* Habilitar e iniciar el servicio podman.socket
* Instalar Python3
* Instalar el paquete podman-compose versión 1.0.6
* Agregue podman-compose a la variable de entorno PATH
* Si usa Red Hat Enterprise Linux 8, verifique que su versión de Podman esté usando Aardvark DNS en lugar de CNI



NOTE: Ajuste el puerto aardvark-dns (predeterminado: 53) después de instalar el agente para evitar conflictos en el puerto DNS.  Siga las instrucciones para configurar el puerto.

.Pasos
. Elimine el paquete podman-docker si está instalado en el host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instalar Podman.
+
Puede obtener Podman desde los repositorios oficiales de Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Donde <versión> es la versión compatible de Podman que estás instalando. <<podman-versions,Ver las versiones compatibles de Podman>> .

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Donde <versión> es la versión compatible de Podman que estás instalando. <<podman-versions,Ver las versiones compatibles de Podman>> .

. Habilite e inicie el servicio podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instalar python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale el paquete del repositorio EPEL si aún no está disponible en su sistema.
. Si utiliza Red Hat Enterprise:
+
Este paso es necesario porque podman-compose está disponible en el repositorio de Paquetes adicionales para Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instalar el paquete podman-compose 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Usando el `dnf install` El comando cumple con el requisito de agregar podman-compose a la variable de entorno PATH.  El comando de instalación agrega podman-compose a /usr/bin, que ya está incluido en el `secure_path` opción en el host.

. Si usa Red Hat Enterprise Linux 8, verifique que su versión de Podman esté usando NetAvark con Aardvark DNS en lugar de CNI.
+
.. Verifique si su networkBackend está configurado en CNI ejecutando el siguiente comando:
+
[source, cli]
----
podman info | grep networkBackend
----
.. Si la red Backend está configurada en `CNI` , tendrás que cambiarlo a `netavark` .
.. Instalar `netavark` y `aardvark-dns` utilizando el siguiente comando:
+
[source, cli]
----
dnf install aardvark-dns netavark
----
.. Abrir el `/etc/containers/containers.conf` archivo y modificar la opción network_backend para usar "netavark" en lugar de "cni".


+
Si `/etc/containers/containers.conf` no existe, realice los cambios de configuración a `/usr/share/containers/containers.conf` .

. Reiniciar podman.
+
[source, cli]
----
systemctl restart podman
----
. Confirme que networkBackend ahora se cambió a "netavark" usando el siguiente comando:
+
[source, cli]
----
podman info | grep networkBackend
----


--
.Motor Docker
--
Siga la documentación de Docker para instalar Docker Engine.

.Pasos
. https://docs.docker.com/engine/install/["Ver instrucciones de instalación desde Docker"^]
+
Siga los pasos para instalar una versión compatible de Docker Engine.  No instale la última versión, ya que la consola no es compatible.

. Verifique que Docker esté habilitado y ejecutándose.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Paso 3: Configurar la red

Configure su red para que el agente de la consola pueda administrar recursos y procesos dentro de su entorno de nube híbrida.  Por ejemplo, debe asegurarse de que haya conexiones disponibles para las redes de destino y que el acceso a Internet saliente esté disponible.

Conexiones a redes de destino:: El agente de consola requiere una conexión de red a la ubicación donde planea crear y administrar sistemas.  Por ejemplo, la red donde planea crear sistemas Cloud Volumes ONTAP o un sistema de almacenamiento en su entorno local.


Acceso a Internet de salida:: La ubicación de red donde implementa el agente de consola debe tener una conexión a Internet saliente para comunicarse con puntos finales específicos.


Puntos finales contactados desde computadoras al usar la consola NetApp basada en web::
+
--
Las computadoras que acceden a la consola desde un navegador web deben tener la capacidad de comunicarse con varios puntos finales.  Necesitará usar la consola para configurar el agente de la consola y para el uso diario de la consola.

link:reference-networking-saas-console.html["Preparar la red para la consola de NetApp"] .

--


Puntos finales contactados desde el agente de la consola:: El agente de la consola requiere acceso a Internet saliente para comunicarse con los siguientes puntos finales para administrar recursos y procesos dentro de su entorno de nube pública para las operaciones diarias.
+
--
Los puntos finales enumerados a continuación son todas entradas CNAME.

[cols="2a,1a"]
|===
| Puntos finales | Objetivo 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Para administrar recursos en Google Cloud.



 a| 
\ https://mysupport.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp .



 a| 
\ https://support.netapp.com
 a| 
Para obtener información de licencias y enviar mensajes de AutoSupport al soporte de NetApp .



 a| 
\ https://signin.b2c.netapp.com
 a| 
Para actualizar las credenciales del sitio de soporte de NetApp (NSS) o para agregar nuevas credenciales de NSS a la consola de NetApp .



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
Proporcionar funciones y servicios dentro de la consola de NetApp .



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obtener imágenes para las actualizaciones del agente de consola.

* Cuando se implementa un nuevo agente, la verificación de validación prueba la conectividad con los puntos finales actuales.  Si utilizaslink:link:reference-networking-saas-console-previous.html["puntos finales anteriores"] , la comprobación de validación falla.  Para evitar este error, omita la comprobación de validación.
+
Aunque los puntos finales anteriores aún son compatibles, NetApp recomienda actualizar las reglas de firewall a los puntos finales actuales lo antes posible. link:reference-networking-saas-console-previous.html#update-endpoint-list["Aprenda a actualizar su lista de puntos finales"] .

* Cuando actualice los puntos finales actuales en su firewall, sus agentes existentes continuarán funcionando.


|===
--


Servidor proxy:: NetApp admite configuraciones de proxy explícitas y transparentes.  Si está utilizando un proxy transparente, solo necesita proporcionar el certificado para el servidor proxy.  Si está utilizando un proxy explícito, también necesitará la dirección IP y las credenciales.
+
--
* Dirección IP
* Cartas credenciales
* Certificado HTTPS


--


Puertos:: No hay tráfico entrante al agente de la consola, a menos que usted lo inicie o si se utiliza como proxy para enviar mensajes de AutoSupport desde Cloud Volumes ONTAP al soporte de NetApp .
+
--
* HTTP (80) y HTTPS (443) brindan acceso a la interfaz de usuario local, que utilizará en circunstancias excepcionales.
* SSH (22) solo es necesario si necesita conectarse al host para solucionar problemas.
* Se requieren conexiones entrantes a través del puerto 3128 si implementa sistemas Cloud Volumes ONTAP en una subred donde no hay una conexión a Internet saliente disponible.
+
Si los sistemas Cloud Volumes ONTAP no tienen una conexión a Internet saliente para enviar mensajes de AutoSupport , la consola configura automáticamente esos sistemas para usar un servidor proxy que está incluido con el agente de la consola.  El único requisito es garantizar que el grupo de seguridad del agente de la consola permita conexiones entrantes a través del puerto 3128.  Necesitará abrir este puerto después de implementar el agente de consola.



--


Habilitar NTP:: Si planea utilizar NetApp Data Classification para escanear sus fuentes de datos corporativos, debe habilitar un servicio de Protocolo de tiempo de red (NTP) tanto en el agente de consola como en el sistema de clasificación de datos de NetApp para que la hora se sincronice entre los sistemas. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Obtenga más información sobre la clasificación de datos de NetApp"^]




== Paso 4: Configurar permisos para el agente de la consola

Se requiere una cuenta de servicio de Google Cloud para proporcionar al agente de la consola los permisos que necesita para administrar recursos en Google Cloud.  Cuando cree el agente de consola, deberá asociar esta cuenta de servicio con la máquina virtual del agente de consola.

Es su responsabilidad actualizar la función personalizada a medida que se agreguen nuevos permisos en versiones posteriores.  Si se requieren nuevos permisos, se enumerarán en las notas de la versión.

.Pasos
. Crear un rol personalizado en Google Cloud:
+
.. Cree un archivo YAML que incluya el contenido delink:reference-permissions-gcp.html["Permisos de cuenta de servicio para el agente de consola"] .
.. Desde Google Cloud, activa Cloud Shell.
.. Sube el archivo YAML que incluye los permisos necesarios.
.. Cree un rol personalizado mediante el uso de `gcloud iam roles create` dominio.
+
El siguiente ejemplo crea un rol denominado "conector" a nivel de proyecto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentación de Google Cloud: Creación y administración de roles personalizados"^]



. Cree una cuenta de servicio en Google Cloud y asígnele el rol:
+
.. Desde el servicio IAM y administración, seleccione *Cuentas de servicio > Crear cuenta de servicio*.
.. Ingrese los detalles de la cuenta de servicio y seleccione *Crear y continuar*.
.. Seleccione el rol que acaba de crear.
.. Complete los pasos restantes para crear el rol.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentación de Google Cloud: Creación de una cuenta de servicio"^]



. Si planea implementar sistemas Cloud Volumes ONTAP en proyectos diferentes al proyecto donde reside el agente de la consola, deberá proporcionar a la cuenta de servicio del agente de la consola acceso a esos proyectos.
+
Por ejemplo, supongamos que el agente de consola está en el proyecto 1 y desea crear sistemas Cloud Volumes ONTAP en el proyecto 2.  Necesitará otorgar acceso a la cuenta de servicio en el proyecto 2.

+
.. Desde el servicio IAM y administración, seleccione el proyecto de Google Cloud donde desea crear sistemas Cloud Volumes ONTAP .
.. En la página *IAM*, seleccione *Otorgar acceso* y proporcione los detalles requeridos.
+
*** Ingrese el correo electrónico de la cuenta de servicio del agente de la consola.
*** Seleccione el rol personalizado del agente de consola.
*** Seleccione *Guardar*.




+
Para más detalles, consulte https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentación de Google Cloud"^]





== Paso 5: Configurar permisos de VPC compartidos

Si está utilizando una VPC compartida para implementar recursos en un proyecto de servicio, deberá preparar sus permisos.

Esta tabla es de referencia y su entorno debe reflejar la tabla de permisos cuando se complete la configuración de IAM.

.Ver permisos de VPC compartidos
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidad | Creador | Alojado en | Permisos del proyecto de servicio | Permisos del proyecto anfitrión | Objetivo 


| Cuenta de Google para implementar el agente | Costumbre | Proyecto de servicio  a| 
link:task-install-connector-google-bluexp-gcloud.html#agent-permissions-google["Política de implementación del agente"]
 a| 
computar.usuariodered
| Implementación del agente en el proyecto de servicio 


| cuenta de servicio del agente | Costumbre | Proyecto de servicio  a| 
link:reference-permissions-gcp.html["Política de cuenta de servicio del agente"]
| Compute.NetworkUser administrador de implementación.editor | Implementación y mantenimiento de Cloud Volumes ONTAP y los servicios en el proyecto de servicio 


| Cuenta de servicio de Cloud Volumes ONTAP | Costumbre | Proyecto de servicio | Miembro de storage.admin: cuenta de servicio de la consola de NetApp como serviceAccount.user | N/A | (Opcional) Para NetApp Cloud Tiering y NetApp Backup and Recovery 


| Agente de servicio de las API de Google | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Interactúa con las API de Google Cloud en nombre de la implementación.  Permite que la consola utilice la red compartida. 


| Cuenta de servicio predeterminada de Google Compute Engine | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Implementa instancias de Google Cloud y la infraestructura computacional en nombre de la implementación.  Permite que la consola utilice la red compartida. 
|===
Notas:

. deploymentmanager.editor solo es necesario en el proyecto host si no pasa reglas de firewall a la implementación y elige dejar que la consola las cree por usted.  La consola de NetApp crea una implementación en el proyecto de host que contiene la regla de firewall VPC0 si no se especifica ninguna regla.
. firewall.create y firewall.delete solo son necesarios si no pasa reglas de firewall a la implementación y elige dejar que la Consola las cree por usted.  Estos permisos residen en el archivo .yaml de la cuenta de la consola.  Si está implementando un par HA mediante una VPC compartida, estos permisos se utilizarán para crear las reglas de firewall para VPC1, 2 y 3.  Para todas las demás implementaciones, estos permisos también se utilizarán para crear reglas para VPC0.
. Para la organización en niveles de nube, la cuenta de servicio de organización en niveles debe tener el rol serviceAccount.user en la cuenta de servicio, no solo en el nivel de proyecto.  Actualmente, si asigna serviceAccount.user en el nivel del proyecto, los permisos no se muestran cuando consulta la cuenta de servicio con getIAMPolicy.


====


== Paso 6: Habilitar las API de Google Cloud

Se deben habilitar varias API de Google Cloud antes de poder implementar sistemas Cloud Volumes ONTAP en Google Cloud.

.Paso
. Habilite las siguientes API de Google Cloud en su proyecto:
+
** API de Cloud Deployment Manager V2
** API de registro en la nube
** API del administrador de recursos en la nube
** API de Compute Engine
** API de gestión de identidad y acceso (IAM)
** API del servicio de administración de claves en la nube (KMS)
+
(Obligatorio solo si planea utilizar NetApp Backup and Recovery con claves de cifrado administradas por el cliente (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentación de Google Cloud: Habilitación de API"^]



== Paso 7: Instalar el agente de consola

Una vez completados los requisitos previos, puede instalar manualmente el software en su propio host Linux.

.Antes de empezar
Debes tener lo siguiente:

* Privilegios de root para instalar el agente de consola.
* Detalles sobre un servidor proxy, si se requiere un proxy para el acceso a Internet desde el agente de la consola.
+
Tiene la opción de configurar un servidor proxy después de la instalación, pero para hacerlo es necesario reiniciar el agente de la consola.

* Un certificado firmado por una CA, si el servidor proxy usa HTTPS o si el proxy es un proxy interceptor.



NOTE: No es posible configurar un certificado para un servidor proxy transparente al instalar manualmente el agente de consola.  Si necesita configurar un certificado para un servidor proxy transparente, debe utilizar la Consola de mantenimiento después de la instalación. Obtenga más información sobre ellink:reference-connector-maint-console.html["Consola de mantenimiento del agente"] .

.Acerca de esta tarea
El instalador que está disponible en el sitio de soporte de NetApp podría ser una versión anterior.  Después de la instalación, el agente de consola se actualiza automáticamente si hay una nueva versión disponible.

.Pasos
. Si las variables del sistema _http_proxy_ o _https_proxy_ están configuradas en el host, elimínelas:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si no elimina estas variables del sistema, la instalación fallará.

. Descargue el software del agente de consola desde https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sitio de soporte de NetApp"^] y luego copiarlo al host Linux.
+
Debe descargar el instalador del agente "en línea" diseñado para su uso en su red o en la nube.

. Asignar permisos para ejecutar el script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Donde <versión> es la versión del agente de consola que descargó.

. Si realiza la instalación en un entorno de nube gubernamental, desactive las comprobaciones de configuración.link:task-troubleshoot-connector.html#disable-config-check["Aprenda cómo deshabilitar las comprobaciones de configuración para instalaciones manuales."]
. Ejecute el script de instalación.
+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Necesitará agregar información de proxy si su red requiere un proxy para acceder a Internet.  Puede agregar un proxy transparente o explícito.  Los parámetros --proxy y --cacert son opcionales y no se le pedirá que los agregue.  Si tiene un servidor proxy, deberá ingresar los parámetros como se muestra.

+
A continuación se muestra un ejemplo de configuración de un servidor proxy explícito con un certificado firmado por una CA:

+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`configura el agente de la consola para utilizar un servidor proxy HTTP o HTTPS utilizando uno de los siguientes formatos:

+
** \http://dirección:puerto
** \http://nombre-de-usuario:contraseña@dirección:puerto
** \http://nombre-de-dominio%92nombre-de-usuario:contraseña@dirección:puerto
** \https://dirección:puerto
** \https://nombre-de-usuario:contraseña@dirección:puerto
** \https://nombre-de-dominio%92nombre-de-usuario:contraseña@dirección:puerto
+
Tenga en cuenta lo siguiente:

+
*** El usuario puede ser un usuario local o un usuario de dominio.
*** Para un usuario de dominio, debe utilizar el código ASCII para un \ como se muestra arriba.
*** El agente de consola no admite nombres de usuario ni contraseñas que incluyan el carácter @.
*** Si la contraseña incluye alguno de los siguientes caracteres especiales, debe escapar ese carácter especial anteponiéndolo con una barra invertida: & o !
+
Por ejemplo:

+
\http://bxpproxyuser:netapp1\!@dirección:3128







`--cacert`Especifica un certificado firmado por CA para usar para el acceso HTTPS entre el agente de consola y el servidor proxy.  Este parámetro es necesario para servidores proxy HTTPS, servidores proxy interceptores y servidores proxy transparentes.

+ Aquí hay un ejemplo de configuración de un servidor proxy transparente.  Cuando configura un proxy transparente, no necesita definir el servidor proxy.  Solo debe agregar un certificado firmado por una CA a su host del agente de consola:

+

[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Si utilizó Podman, necesitará ajustar el puerto aardvark-dns.
+
.. SSH a la máquina virtual del agente de consola.
.. Abra el archivo podman _/usr/share/containers/containers.conf_ y modifique el puerto elegido para el servicio DNS de Aardvark.  Por ejemplo, cámbielo a 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Reinicie la máquina virtual del agente de consola.


. Espere a que se complete la instalación.
+
Al final de la instalación, el servicio del agente de consola (occm) se reinicia dos veces si especificó un servidor proxy.




NOTE: Si la instalación falla, puede ver el informe de instalación y los registros para ayudarlo a solucionar los problemas.link:task-troubleshoot-connector.html#troubleshoot-installation["Aprenda a solucionar problemas de instalación."]

. Abra un navegador web desde un host que tenga una conexión a la máquina virtual del agente de consola e ingrese la siguiente URL:
+
https://_ipaddress_[]

. Después de iniciar sesión, configure el agente de la consola:
+
.. Especifique la organización que se asociará con el agente de la consola.
.. Introduzca un nombre para el sistema.
.. En *¿Está ejecutando en un entorno seguro?* mantenga el modo restringido deshabilitado.
+
Debes mantener el modo restringido deshabilitado porque estos pasos describen cómo usar la consola en modo estándar.  Debe habilitar el modo restringido solo si tiene un entorno seguro y desea desconectar esta cuenta de los servicios de backend.  Si ese es el caso,link:task-quick-start-restricted-mode.html["Siga los pasos para comenzar a utilizar la consola de NetApp en modo restringido"] .

.. Seleccione *Comencemos*.


+

NOTE: Si la instalación falla, puede ver registros y un informe para ayudarlo a solucionar problemas.link:task-troubleshoot-connector.html#troubleshoot-installation["Aprenda a solucionar problemas de instalación."]



Si tiene depósitos de Google Cloud Storage en la misma cuenta de Google Cloud donde creó el agente de consola, verá aparecer automáticamente un sistema de Google Cloud Storage en la página *Sistemas*. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["Aprenda a administrar Google Cloud Storage desde la consola de NetApp"^]



== Paso 8: Proporcionar permisos al agente de la consola

Debes proporcionar al agente de la consola los permisos de Google Cloud que configuraste previamente.  Al proporcionar los permisos, se permite que el agente de la consola administre sus datos y la infraestructura de almacenamiento en Google Cloud.

.Pasos
. Vaya al portal de Google Cloud y asigne la cuenta de servicio a la instancia de VM del agente de consola.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentación de Google Cloud: Cómo cambiar la cuenta de servicio y los ámbitos de acceso de una instancia"^]

. Si desea administrar recursos en otros proyectos de Google Cloud, otorgue acceso agregando la cuenta de servicio con el rol de agente de consola a ese proyecto. Necesitarás repetir este paso para cada proyecto.

