---
sidebar: sidebar 
permalink: task-install-agent-aws-console.html 
keywords: deploy agent, aws agent deployment, aws agent, deploy agent in aws, bluexp, create agent, NetApp Console 
summary: Puedes implementar un agente de Console en AWS directamente desde la NetApp Console. Antes de implementar un agente de Console en AWS desde la Console, necesitas configurar tu red y preparar los permisos de AWS. 
---
= Implementa un agente de consola en AWS desde NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puedes implementar un agente de Console en AWS directamente desde la NetApp Console. Antes de implementar un agente de Console en AWS desde la Console, necesitas configurar tu red y preparar los permisos de AWS.

La implementación de un agente en AWS lanza una instancia EC2 que ejecuta Linux y el software del agente de la consola en una VPC de tu elección.

.Antes de empezar
* link:concept-agent-install-options.html#agent-console-deploy["Aprende cuándo desplegar desde la consola"].
* Deberías revisarlolink:reference-limitations.html["Limitaciones del agente de consola"] .




== Paso 1: Configurar la red para implementar un agente de consola en AWS

Asegúrese de que la ubicación de red donde planea instalar el agente de consola admita los siguientes requisitos.  Estos requisitos permiten que el agente de la consola administre recursos y procesos en su nube híbrida.

VPC y subred:: Cuando crea el agente de consola, debe especificar la VPC y la subred donde debe residir.


Conexiones a redes de destino:: El agente de consola requiere una conexión de red a la ubicación donde planea crear y administrar sistemas.  Por ejemplo, la red donde planea crear sistemas Cloud Volumes ONTAP o un sistema de almacenamiento en su entorno local.


Acceso a Internet de salida:: La ubicación de red donde implementa el agente de consola debe tener una conexión a Internet saliente para comunicarse con puntos finales específicos.


Puntos finales contactados desde el agente de la consola:: El agente de la consola requiere acceso a Internet saliente para comunicarse con los siguientes puntos finales para administrar recursos y procesos dentro de su entorno de nube pública para las operaciones diarias.
+
--
Los puntos finales enumerados a continuación son todas entradas CNAME.

[cols="2a,1a"]
|===
| Puntos finales | Objetivo 


 a| 
Servicios de AWS (amazonaws.com):

* Formación de nubes
* Nube de cómputo elástica (EC2)
* Gestión de identidad y acceso (IAM)
* Servicio de gestión de claves (KMS)
* Servicio de token de seguridad (STS)
* Servicio de almacenamiento simple (S3)

 a| 
Para administrar los recursos de AWS.  El punto final depende de su región de AWS. https://docs.aws.amazon.com/general/latest/gr/rande.html["Consulte la documentación de AWS para obtener más detalles."^]



 a| 
Amazon FSx for NetApp ONTAP:

* api.workloads.netapp.com

 a| 
La consola basada en web se comunica con este punto final para interactuar con las API de Workload Factory para administrar y operar cargas de trabajo basadas en FSx para ONTAP.



 a| 
\ https://mysupport.netapp.com
 a| 
Para obtener información sobre licencias y enviar mensajes de AutoSupport al soporte de NetApp.



 a| 
\ https://signin.b2c.netapp.com
 a| 
Para actualizar las credenciales del sitio de soporte de NetApp (NSS) o para agregar nuevas credenciales de NSS a la NetApp Console.



 a| 
\ https://support.netapp.com
 a| 
Para obtener información sobre licencias y enviar mensajes de AutoSupport al soporte de NetApp, así como para recibir actualizaciones de software para Cloud Volumes ONTAP.



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com
 a| 
Proporcionar funciones y servicios dentro de la NetApp Console.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Para obtener imágenes para las actualizaciones del agente de consola.

|===
--


Puntos finales contactados desde la consola de NetApp:: A medida que usas la aplicación SaaS NetApp Console basada en web, esta se pone en contacto con varios endpoints para completar tareas de gestión de datos. Esto incluye endpoints con los que se contacta para desplegar el agente de la Console desde la Console.
+
--
link:reference-networking-saas-console.html["Ver la lista de puntos finales contactados desde la NetApp Console"].

--


Servidor proxy:: NetApp admite configuraciones de proxy explícitas y transparentes.  Si está utilizando un proxy transparente, solo necesita proporcionar el certificado para el servidor proxy.  Si está utilizando un proxy explícito, también necesitará la dirección IP y las credenciales.
+
--
* Dirección IP
* Cartas credenciales
* Certificado HTTPS


--


Puertos:: No hay tráfico entrante al agente de la Consola, a menos que tú lo inicies o se utilice como proxy para enviar mensajes de AutoSupport desde Cloud Volumes ONTAP a NetApp Support.
+
--
* HTTP (80) y HTTPS (443) brindan acceso a la interfaz de usuario local, que utilizará en circunstancias excepcionales.
* SSH (22) solo es necesario si necesita conectarse al host para solucionar problemas.
* Se requieren conexiones entrantes a través del puerto 3128 si implementa sistemas Cloud Volumes ONTAP en una subred donde no hay una conexión a Internet saliente disponible.
+
Si los sistemas Cloud Volumes ONTAP no tienen una conexión a Internet saliente para enviar mensajes de AutoSupport , la consola configura automáticamente esos sistemas para usar un servidor proxy que está incluido con el agente de la consola.  El único requisito es garantizar que el grupo de seguridad del agente de la consola permita conexiones entrantes a través del puerto 3128.  Necesitará abrir este puerto después de implementar el agente de consola.



--


Habilitar NTP:: Si tienes pensado usar NetApp Data Classification para analizar tus fuentes de datos corporativas, deberías habilitar un servicio de Network Time Protocol (NTP) tanto en el agente de la Console como en el sistema NetApp Data Classification para que la hora esté sincronizada entre los sistemas. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Más información sobre NetApp Data Classification"^].
+
--
Necesitará implementar este requisito de red después de crear el agente de consola.

--




== Paso 2: Configurar los permisos de AWS para el agente de la consola

La consola debe autenticarse con AWS antes de poder implementar el agente de la consola en su VPC. Puede elegir uno de estos métodos de autenticación:

* Deje que la consola asuma un rol de IAM que tenga los permisos necesarios
* Proporcionar una clave de acceso de AWS y una clave secreta para un usuario de IAM que tenga los permisos necesarios


Con cualquiera de las opciones, el primer paso es crear una política de IAM. Esta política contiene solo los permisos necesarios para iniciar el agente de la consola en AWS desde la consola.

Si es necesario, puede restringir la política de IAM mediante el IAM `Condition` elemento. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["Documentación de AWS: Elemento de condición"^]

.Pasos
. Vaya a la consola de AWS IAM.
. Seleccione *Políticas > Crear política*.
. Seleccione *JSON*.
. Copie y pegue la siguiente política:
+
Esta política contiene solo los permisos necesarios para iniciar el agente de la consola en AWS desde la consola.  Cuando la consola crea el agente de consola, aplica un nuevo conjunto de permisos al agente de consola que le permite administrar los recursos de AWS. link:reference-permissions-aws.html["Ver los permisos necesarios para el propio agente de la consola"].

+
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iam:CreateRole",
        "iam:DeleteRole",
        "iam:PutRolePolicy",
        "iam:CreateInstanceProfile",
        "iam:DeleteRolePolicy",
        "iam:AddRoleToInstanceProfile",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:DeleteInstanceProfile",
        "iam:PassRole",
        "iam:ListRoles",
        "ec2:DescribeInstanceStatus",
        "ec2:RunInstances",
        "ec2:ModifyInstanceAttribute",
        "ec2:CreateSecurityGroup",
        "ec2:DeleteSecurityGroup",
        "ec2:DescribeSecurityGroups",
        "ec2:RevokeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface",
        "ec2:ModifyNetworkInterfaceAttribute",
        "ec2:DescribeSubnets",
        "ec2:DescribeVpcs",
        "ec2:DescribeDhcpOptions",
        "ec2:DescribeKeyPairs",
        "ec2:DescribeRegions",
        "ec2:DescribeInstances",
        "ec2:CreateTags",
        "ec2:DescribeImages",
        "ec2:DescribeAvailabilityZones",
        "ec2:DescribeLaunchTemplates",
        "ec2:CreateLaunchTemplate",
        "cloudformation:CreateStack",
        "cloudformation:DeleteStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackEvents",
        "cloudformation:ValidateTemplate",
        "ec2:AssociateIamInstanceProfile",
        "ec2:DescribeIamInstanceProfileAssociations",
        "ec2:DisassociateIamInstanceProfile",
        "iam:GetRole",
        "iam:TagRole",
        "kms:ListAliases",
        "cloudformation:ListStacks"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:TerminateInstances"
      ],
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/OCCMInstance": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    }
  ]
}
----
. Seleccione *Siguiente* y agregue etiquetas, si es necesario.
. Seleccione *Siguiente* e ingrese un nombre y una descripción.
. Seleccione *Crear política*.
. Adjunte la política a un rol de IAM que la consola pueda asumir o a un usuario de IAM para poder proporcionar a la consola claves de acceso:
+
** (Opción 1) Configure un rol de IAM que la consola pueda asumir:
+
... Vaya a la consola de AWS IAM en la cuenta de destino.
... En Administración de acceso, seleccione *Roles > Crear rol* y siga los pasos para crear el rol.
... En *Tipo de entidad confiable*, seleccione *Cuenta AWS*.
... Seleccione *Otra cuenta de AWS* e ingrese el ID de la cuenta SaaS de la consola: 952013314444
... Seleccione la política que creó en la sección anterior.
... Después de crear el rol, copie el ARN del rol para poder pegarlo en la consola cuando cree el agente de la consola.


** (Opción 2) Configure permisos para un usuario de IAM para que pueda proporcionar a la consola claves de acceso:
+
... Desde la consola de AWS IAM, seleccione *Usuarios* y luego seleccione el nombre de usuario.
... Seleccione *Agregar permisos > Adjuntar políticas existentes directamente*.
... Seleccione la política que ha creado.
... Seleccione *Siguiente* y luego seleccione *Agregar permisos*.
... Asegúrese de tener la clave de acceso y la clave secreta del usuario de IAM.






.Resultado
Ahora debería tener un rol de IAM que tenga los permisos necesarios o un usuario de IAM que tenga los permisos necesarios.  Al crear el agente de la consola desde la consola, puede proporcionar información sobre el rol o las claves de acceso.



== Paso 3: Crear el agente de consola

Crea el agente de Console directamente desde la consola web de Console.

.Acerca de esta tarea
* Al crear el agente de la consola desde la consola, se implementa una instancia EC2 en AWS utilizando una configuración predeterminada.  No cambie a una instancia EC2 más pequeña con menos CPU o menos RAM después de crear el agente de consola. link:reference-agent-default-config.html["Obtenga información sobre la configuración predeterminada para el agente de la consola"] .
* Cuando la consola crea el agente de consola, crea un rol de IAM y un perfil para el agente. Esta función incluye permisos que permiten al agente de la consola administrar los recursos de AWS. Asegúrese de que la función se actualice a medida que se agreguen nuevos permisos en futuras versiones. link:reference-permissions-aws.html["Obtenga más información sobre la política de IAM para el agente de consola"].


.Antes de empezar
Debes tener lo siguiente:

* Un método de autenticación de AWS: un rol de IAM o claves de acceso para un usuario de IAM con los permisos requeridos.
* Una VPC y una subred que cumple con los requisitos de red.
* Un par de claves para la instancia EC2.
* Detalles sobre un servidor proxy, si se requiere un proxy para el acceso a Internet desde el agente de la consola.
* Configuraciónlink:#networking-aws-agent["requisitos de red"] .
* Configuraciónlink:#aws-permissions-agent["Permisos de AWS"] .


.Pasos
. Seleccione *Administración > Agentes*.
. En la página *Overview*, selecciona *Deploy agent > AWS*.
. Siga los pasos del asistente para crear el agente de consola:
. En la página *Introducción*, revisa la descripción general del proceso.
. En la página *Credenciales de AWS*, especifica tu región de AWS y luego elige un método de autenticación, que puede ser un rol de IAM que NetApp Console pueda asumir o una clave de acceso y una clave secreta de AWS.
+

TIP: Si elige *Asumir rol*, puede crear el primer conjunto de credenciales desde el asistente de implementación del agente de la consola.  Cualquier conjunto adicional de credenciales debe crearse desde la página Credenciales.  Luego estarán disponibles en una lista desplegable del asistente. link:task-adding-aws-accounts.html["Aprenda cómo agregar credenciales adicionales"] .

. En la página *Detalles*, proporcione detalles sobre el agente de consola.
+
** Introduzca un nombre.
** Añadir etiquetas personalizadas (metadatos).
** Elija si desea que la Consola cree un nuevo rol que tenga los permisos necesarios o si desea seleccionar un rol existente que haya configurado conlink:reference-permissions-aws.html["los permisos requeridos"] .
** Elija si desea cifrar los discos EBS del agente de consola.  Tiene la opción de utilizar la clave de cifrado predeterminada o utilizar una clave personalizada.


. En la página *Red*, especifica una VPC, una subred y un par de claves para el agente, elige si quieres habilitar una dirección IP pública y, opcionalmente, especifica una configuración de proxy.
+
Asegúrese de tener el par de claves correcto para acceder a la máquina virtual del agente de consola.  Sin un par de claves, no puedes acceder a él.

. En la página *Grupo de seguridad*, elija si desea crear un nuevo grupo de seguridad o si desea seleccionar un grupo de seguridad existente que permita las reglas de entrada y salida requeridas.
+
link:reference-ports-aws.html["Ver las reglas del grupo de seguridad para AWS"] .

. Revisa tus selecciones para verificar que tu configuración es correcta.
+
.. La casilla de comprobación *Validar configuración del agente* está seleccionada de forma predeterminada para que la Console valide los requisitos de conectividad de red cuando despliegas. Si la Console no puede desplegar el agente, te proporciona un informe para ayudarte a solucionar el problema. Si el despliegue se realiza correctamente, no se proporciona ningún informe.


+
[NOTE]
====
** Si todavía estás usando la link:reference-networking-saas-console-previous.html["puntos finales anteriores"] utilizada para las actualizaciones de agentes, la validación falla con un error. Para evitar esto, desmarca la casilla de comprobación para omitir la comprobación de validación.
** Durante la instalación, NetApp comprueba que el host del agente tenga al menos el 80 por ciento del espacio en disco total disponible, lo que incluye 48 GB en `/opt` y 32 GB en `/var` (80 GB en total). Después de la instalación, requiere que al menos el 20 por ciento del disco total permanezca disponible, lo que incluye 12 GB en `/opt` y 8 GB en `/var` (20 GB en total).


====
. Seleccione *Agregar*.
+
La consola implementa el agente en aproximadamente 10 minutos. Permanezca en la página hasta que se complete el proceso.



.Resultado
Una vez completado el proceso, el agente de la consola estará disponible para su uso desde la consola.


NOTE: Si la implementación falla, puedes descargar un informe y registros desde la Consola para ayudarte a solucionar los problemas.link:task-troubleshoot-agent.html#troubleshoot-installation["Aprenda a solucionar problemas de instalación."]

Si tiene depósitos de Amazon S3 en la misma cuenta de AWS donde creó el agente de consola, verá aparecer automáticamente un entorno de trabajo de Amazon S3 en la página *Sistemas*. https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Aprenda a administrar los buckets S3 desde la NetApp Console"^]
