---
sidebar: sidebar 
permalink: task-upgrade-agent.html 
keywords: upgrade, manual upgrade, agent upgrade, manual agent upgrade, upgrade agent manually, private mode upgrade, offline upgrade, upgrade private mode, connector upgrade, agent upgrade 
summary: 'El agente de la Consola se actualiza automáticamente cuando tiene conectividad saliente. Si tu agente de la Consola no tiene conectividad saliente, puedes actualizarlo manualmente (como con el modo privado).' 
---
= Administrar actualizaciones del agente de la consola
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El agente de la Consola se actualiza automáticamente cuando tiene conectividad saliente. Si tu agente de la Consola no tiene conectividad saliente, puedes actualizarlo manualmente (como con el modo privado).



== Actualizar el agente de la consola

El agente de la consola debe reiniciarse durante el proceso de actualización, por lo que la NetApp Console no ​​estará disponible durante la actualización.

.Pasos
. Descargue el software del agente de consola desde https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sitio de soporte de NetApp"^] .
. Copie el instalador al host Linux.
. Asignar permisos para ejecutar el script.
+
[source, cli]
----
chmod +x /path/NetApp-Console-Agent-Offline-<version>
----
+
Donde <versión> es la versión del agente de consola que descargó.

. Ejecute el script de instalación:
+
[source, cli]
----
sudo /path/NetApp-Console-Agent-Offline-<version>
----
+
Donde <versión> es la versión del agente que descargaste.

. Una vez completada la actualización, puede verificar la versión del agente yendo a *Administración > Soporte > Agentes*.

