---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Después de registrarse en la NetApp Console, puede iniciar sesión desde la consola basada en web para comenzar a administrar sus datos y su infraestructura de almacenamiento. 
---
= Iniciar sesión en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de registrarse en la NetApp Console, puede iniciar sesión desde la consola basada en web para comenzar a administrar sus datos y su infraestructura de almacenamiento.

Después de que te registres, el administrador de la organización de Console debe agregar tu cuenta de usuario a una organización antes de que puedas acceder a cualquier recurso. Si inicias sesión pero no ves ningún recurso, contacta al administrador de tu organización. link:task-user-settings.html#contact-admin["Contacta al administrador de tu organización"].

.Pasos
. Ve a la URL de la consola NetApp. La URL depende de qué modo de la consola esté usando tu organización:
+
** *Modo estándar*: Abre un navegador web y ve a la https://console.netapp.com["NetApp Console"^].
** **Modo restringido o modo privado**: abre un navegador web y ve a la dirección IP donde está instalado el agente de la NetApp Console.


. En la página *Iniciar sesión*, ingrese la dirección de correo electrónico asociada con su inicio de sesión.
. Dependiendo del método de autenticación asociado a tu inicio de sesión, se te pedirá que introduzcas tus credenciales.
+
** Sus credenciales existentes del sitio de soporte de NetApp (NSS)
** Una cuenta de NetApp Console que utiliza su dirección de correo electrónico y una contraseña
** Una conexión federada si tu administrador ha configurado la federación de identidades para tu organización



