---
sidebar: sidebar 
permalink: task-federation-verify-domain.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: Si quieres federarte con un dominio que es diferente de tu dominio de correo electrónico, primero debes verificar que eres el propietario del dominio. Solo puedes usar dominios verificados para la federación. 
---
= Verifica tu dominio de correo electrónico para la federación en NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si quieres federarte con un dominio que es diferente de tu dominio de correo electrónico, primero debes verificar que eres el propietario del dominio. Solo puedes usar dominios verificados para la federación.

.Roles requeridos
El rol de administrador de la Federación es necesario para crear y gestionar federaciones. El visor de la Federación puede ver la página de la Federación. link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso."]

Para verificar su dominio es necesario agregar un registro TXT a la configuración de DNS de su dominio.  Este registro se utiliza para demostrar que usted es el propietario del dominio y permite que la NetApp Console confíe en el dominio para la federación.  Es posible que necesite coordinar con su administrador de TI o de red para completar este paso.

Por ejemplo, si usas Microsoft Entra ID, puedes seguir los pasos indicados en la documentación de Microsoft https://learn.microsoft.com/en-us/entra/fundamentals/add-custom-domain["Agrega un dominio con Microsoft Entra ID"^].

.Pasos
. Seleccione *Administración > Identidad y acceso*.
. Seleccione *Federación* para ver la página *Federaciones*.
. Seleccione *Configurar nueva federación*.
. Seleccione *Verificar propiedad del dominio*.
. Ingrese el dominio que desea verificar y seleccione *Continuar*.
. Copie el registro TXT que se proporciona.
. Vaya a la configuración de DNS de su dominio y configure el valor TXT que se proporcionó como registro TXT para su dominio.  Trabaje con su administrador de TI o de red si es necesario.
. Después de agregar el registro TXT, regrese a la Consola y seleccione *Verificar*.

