---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: Administre los miembros de su organización para otorgar permisos en diferentes niveles de la jerarquía de recursos de su organización. 
---
= Agregar usuarios a una organización de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dentro de la consola, usted otorga a los usuarios acceso a proyectos o carpetas según un rol de acceso. Un _rol de acceso_ contiene un conjunto de permisos que permiten a un miembro (usuario o cuenta de servicio) realizar acciones específicas en el nivel asignado de la jerarquía de recursos.

.Roles de acceso requeridos
Superadministrador, administrador de la organización o administrador de carpeta o proyecto (para carpetas y proyectos que administra). link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso"].



== Comprenda cómo se otorga el acceso en la NetApp Console

La NetApp Console utiliza el control de acceso basado en roles (RBAC) para administrar los permisos. Asignar roles a los usuarios individualmente o a través de grupos federados. Cada rol define acciones permitidas para recursos específicos.

Tenga en cuenta lo siguiente sobre cómo conceder acceso en la NetApp Console:

* Todos los usuarios deben registrarse primero en la NetApp Console antes de poder obtener acceso a los recursos.
* Debe asignar explícitamente un rol a cada usuario en la Consola antes de que puedan acceder a los recursos, incluso si son miembros de un grupo federado al que se le ha asignado un rol.
* Puede agregar cuentas de servicio directamente desde la consola y asignarles roles.




== Agregue miembros a su organización

La NetApp Console admite tres tipos de miembros: cuentas de usuario, cuentas de servicio y grupos federados.

Los usuarios deben registrarse en NetApp Console antes de poder agregarlos y asignarles un rol, incluso si están en un grupo federado. Cree cuentas de servicio directamente en la consola.

Todos los miembros deben tener al menos un rol asignado explícitamente para poder acceder a los recursos.

Al agregar un miembro, elija el nivel de recurso (organización, carpeta o proyecto) y asigne un rol o roles con los permisos necesarios.



=== Agregar un usuario

Los usuarios se registran en la NetApp Console, pero un administrador de organización, carpeta o proyecto debe agregarlos a una organización, carpeta o proyecto para que puedan acceder a los recursos.

.Antes de empezar:
El usuario ya debe haberse registrado en la NetApp Console. Si aún no se han registrado, diríjalos a link:task-sign-up-saas.html["Regístrese en la NetApp Console."]


NOTE: Si está agregando un usuario que forma parte de un grupo federado, asegúrese de que el usuario ya se haya registrado en la NetApp Console y se le haya asignado explícitamente un rol en la consola. NetApp recomienda asignar un rol de acceso mínimo, como Visor de la organización.

.Pasos
. Seleccione *Administración > Identidad y acceso*.
. Seleccione *Miembros*.
. Seleccione *Agregar un miembro*.
. Para *Tipo de miembro*, mantenga *Usuario* seleccionado.
. Para *Correo electrónico del usuario*, ingrese la dirección de correo electrónico del usuario asociada con el inicio de sesión que creó.
. Utilice la sección *Seleccionar una organización, carpeta o proyecto* para elegir el nivel de su jerarquía de recursos para el cual el miembro debe tener permisos.
+
Tenga en cuenta lo siguiente:

+
** Puede seleccionar sólo las carpetas y proyectos para los que tenga permisos.
** Cuando selecciona una organización o carpeta, otorga al miembro permisos sobre todo su contenido.
** Solo puedes asignar el rol de *Administrador de la organización* a nivel de organización.


. *Seleccione una categoría* y luego seleccione un *Rol* que proporcione al miembro permisos para los recursos asociados con la organización, carpeta o proyecto que seleccionó.
+
link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso"] .

. Para dar acceso a más carpetas, proyectos o roles, seleccione *Agregar rol*, elija la carpeta, el proyecto o la categoría de rol y seleccione un rol.
. Seleccione *Agregar*.
+
La consola envía instrucciones por correo electrónico al usuario.





=== Agregar una cuenta de servicio

Las cuentas de servicio le permiten automatizar tareas y conectarse de forma segura con las API de la consola. Elija un ID de cliente y un secreto para configuraciones simples, o JWT (JSON Web Token) para una mayor seguridad en entornos automatizados o nativos de la nube. Seleccione el método que cumpla con sus requisitos de seguridad.

.Antes de empezar:
Para la autenticación JWT, prepare su clave pública o certificado.

.Pasos
. Seleccione *Administración > Identidad y acceso*.
. Seleccione *Miembros*.
. Seleccione *Agregar un miembro*.
. Para *Tipo de miembro*, seleccione *Cuenta de servicio*.
. Introduzca un nombre para la cuenta de servicio.
. Para utilizar la autenticación JWT, seleccione *Usar autenticación JWT de clave privada* y cargue su clave RSA pública o certificado. Omitir si se utiliza el ID del cliente y el secreto.
+
Su certificado X.509. Debe estar en formato PEM, CRT o CER.

+
.. Configure notificaciones de vencimiento para su certificado.  Elija entre siete días o 30 días.  Las notificaciones de vencimiento se envían por correo electrónico y se muestran en la consola a los usuarios con el rol de superadministrador o administrador de la organización.


. Utilice la sección *Seleccionar una organización, carpeta o proyecto* para elegir el nivel de su jerarquía de recursos para el cual el miembro debe tener permisos.
+
Tenga en cuenta lo siguiente:

+
** Sólo puedes seleccionar entre las carpetas y proyectos para los que tienes permisos.
** Al seleccionar una organización o carpeta, se otorgan al miembro permisos sobre todo su contenido.
** Solo puedes asignar el rol de *Administrador de la organización* a nivel de organización.


. Seleccione una *Categoría* y luego seleccione un *Rol* que le otorgue al miembro permisos para los recursos en la organización, carpeta o proyecto que usted seleccionó.
+
link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso"] .

. Para dar acceso a más carpetas, proyectos o roles, seleccione *Agregar rol*, elija la carpeta, el proyecto o la categoría de rol y seleccione un rol.
. Si no eligió utilizar la autenticación JWT, descargue o copie el ID del cliente y el secreto del cliente.
+
La consola muestra el secreto del cliente solo una vez. Cópielo de forma segura; podrá volver a crearlo más tarde si lo pierde.

. Si eligió la autenticación JWT, descargue o copie el ID del cliente y la audiencia JWT. La consola muestra esta información solo una vez y no permite recuperarla más tarde.
. Seleccione *Cerrar*.




== Agregue un grupo federado a su organización

Puede agregar un grupo federado de su proveedor de identidad (IdP) a su organización y asignarle uno o más roles. Los miembros del grupo federado heredan los roles que usted asigna al grupo en la Consola.


IMPORTANT: Cuando agregas un grupo federado a la Consola y le asignas un rol, solo los usuarios que son miembros del grupo en tu IdP y que ya se han registrado en la NetApp Console y se les ha asignado explícitamente un rol en la Consola pueden acceder a los recursos. NetApp recomienda asignar un rol de acceso mínimo, como organization viewer, a estos usuarios.

Antes de poder asignar un rol a un grupo federado, asegúrese de lo siguiente:

* Configure la federación entre su IdP y la consola. link:concept-federation.html["Aprenda cómo configurar la federación."]
* El grupo ya debe existir en su IdP y debe tener asignado acceso a la aplicación de la Consola.


.Pasos
. Seleccione *Administración > Identidad y acceso*.
. Seleccione *Miembros*.
. Seleccione *Agregar un miembro*.
. Para *Tipo de miembro*, seleccione *Grupo federado*.
. Seleccione la federación de la que es miembro el grupo
. Para *Nombre del grupo*, ingrese el nombre exacto del grupo en su IdP.
. Utilice la sección *Seleccionar una organización, carpeta o proyecto* para elegir el nivel de su jerarquía de recursos para el cual el miembro debe tener permisos.
+
Tenga en cuenta lo siguiente:

+
** Sólo puedes seleccionar entre las carpetas y proyectos para los que tienes permisos.
** Al seleccionar una organización o carpeta, se otorgan al miembro permisos sobre todo su contenido.
** Solo puedes asignar el rol de *Administrador de la organización* a nivel de organización.


. Seleccione una *Categoría* y luego seleccione un *Rol* que le otorgue al miembro permisos para los recursos en la organización, carpeta o proyecto que usted seleccionó.
+
link:reference-iam-predefined-roles.html["Obtenga más información sobre los roles de acceso"] .

. Para dar acceso a más carpetas, proyectos o roles, seleccione *Agregar rol*, elija la carpeta, el proyecto o la categoría de rol y seleccione un rol.




== Información relacionada

* link:concept-identity-and-access-management.html["Obtenga información sobre la gestión de identidad y acceso en la NetApp Console"]
* link:task-iam-get-started.html["Comience con la identidad y el acceso"]
* link:reference-iam-predefined-roles.html["Roles de acceso a la NetApp Console"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["Conozca la API para identidad y acceso"^]

