---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'Según las acciones que haya realizado en la consola, es posible que haya asociado las credenciales de ONTAP y las credenciales del sitio de soporte de NetApp (NSS) con su inicio de sesión de usuario.  Puede ver y administrar esas credenciales después de haberlas asociado.  Por ejemplo, si cambia la contraseña de estas credenciales, deberá actualizar la contraseña en la Consola.' 
---
= Administrar las credenciales asociadas con el inicio de sesión de su consola de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Según las acciones que haya realizado en la consola, es posible que haya asociado las credenciales de ONTAP y las credenciales del sitio de soporte de NetApp (NSS) con su inicio de sesión de usuario.  Puede ver y administrar esas credenciales después de haberlas asociado.  Por ejemplo, si cambia la contraseña de estas credenciales, deberá actualizar la contraseña en la Consola.



== Credenciales de ONTAP

Los usuarios necesitan credenciales de administrador de ONTAP para descubrir clústeres de ONTAP en la consola.  Sin embargo, el acceso a ONTAP System Manager depende de si está utilizando o no un agente de consola.

.Sin un agente de consola
Se solicita a los usuarios que ingresen sus credenciales de ONTAP para acceder a ONTAP System Manager para el clúster.  Los usuarios pueden elegir guardar estas credenciales en la consola, lo que significa que no se les solicitará que las ingresen cada vez.  Las credenciales de usuario solo son visibles para el usuario respectivo y se pueden administrar desde la página Credenciales de usuario.

.Con un agente de consola
De forma predeterminada, no se solicita a los usuarios que ingresen sus credenciales de ONTAP para acceder a ONTAP System Manager.  Sin embargo, un administrador de la consola (con el rol de administrador de la organización) puede configurar la consola para solicitar a los usuarios que ingresen sus credenciales de ONTAP .  Cuando esta configuración está habilitada, los usuarios deben ingresar sus credenciales de ONTAP cada vez.

link:task-ontap-access-connector.html["Más información."^]



== Credenciales de NSS

Las credenciales de NSS asociadas con su inicio de sesión en la consola de NetApp permiten el registro de soporte, la gestión de casos y el acceso a Digital Advisor.

* Cuando accede a *Soporte > Recursos* y se registra para recibir soporte, se le solicita que asocie las credenciales de NSS con su inicio de sesión.
+
Esto registra su organización o cuenta para recibir soporte y activa el derecho a soporte.  Solo un usuario de su organización debe asociar una cuenta del sitio de soporte de NetApp con su inicio de sesión para registrarse para recibir soporte y activar el derecho a soporte.  Una vez completado esto, la página *Recursos* mostrará que su cuenta está registrada para recibir soporte.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Aprenda cómo registrarse para recibir soporte"^]

* Cuando acceda a *Administración > Soporte > Gestión de casos*, se le solicitará que ingrese sus credenciales de NSS, si aún no lo ha hecho.  Esta página le permite crear y administrar los casos de soporte asociados con su cuenta NSS y con su empresa.
* Cuando accede a Digital Advisor en la consola, se le solicita que inicie sesión en Digital Advisor ingresando sus credenciales de NSS.


Tenga en cuenta lo siguiente sobre la cuenta NSS asociada con su inicio de sesión:

* La cuenta se administra a nivel de usuario, lo que significa que no puede ser vista por otros usuarios que inicien sesión.
* Solo puede haber una cuenta NSS asociada con Digital Advisor y la gestión de casos de soporte por usuario.
* Si intenta asociar una cuenta del sitio de soporte de NetApp con un sistema Cloud Volumes ONTAP , solo puede elegir entre las cuentas NSS que se agregaron a la organización de la que es miembro.
+
Las credenciales de nivel de cuenta NSS son diferentes a las de la cuenta NSS asociada con su inicio de sesión.  Las credenciales de nivel de cuenta de NSS le permiten implementar Cloud Volumes ONTAP con BYOL, registrar sistemas PAYGO y actualizar su software.

+
link:task-adding-nss-accounts.html["Obtenga más información sobre el uso de credenciales NSS con su organización o cuenta de NetApp Console"] .





== Administra tus credenciales de usuario

Administre sus credenciales de usuario actualizando el nombre de usuario y la contraseña o eliminando las credenciales.

.Pasos
. Seleccione *Administración > Credenciales*.
. Seleccione *Credenciales de usuario*.
. Si aún no tiene credenciales de usuario, puede seleccionar *Agregar credenciales NSS* para agregar su cuenta del sitio de soporte de NetApp .
. Administre las credenciales existentes eligiendo las siguientes opciones en el menú Acciones:
+
** *Actualizar credenciales*: Actualice el nombre de usuario y la contraseña de la cuenta.
** *Eliminar credenciales*: elimina la cuenta NSS asociada con tu inicio de sesión en la consola.



