---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'Si es la primera vez que utiliza la NetApp Console, el asistente de la consola lo guiará a través del proceso de configuración inicial.  El asistente le ayuda a agregar una cuenta de NetApp Support Site (NSS), agregar un agente de consola, agregar un clúster y agregar una licencia o suscripción, lo que facilita el inicio de la administración de sus datos.' 
---
= Comience a utilizar el asistente de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si es la primera vez que utiliza la NetApp Console (SaaS) con el rol de administrador de la organización, puede usar el asistente de la consola para que lo guíe a través del proceso de configuración inicial. El asistente le ayuda a agregar una cuenta de NetApp Support Site (NSS), agregar un agente de consola, agregar un clúster y agregar una licencia o suscripción, lo que facilita el inicio de la administración de sus datos.



== Roles necesarios para acceder al asistente de la consola

El asistente de consola solo está disponible para usuarios con el rol de administrador de la organización.

De forma predeterminada, la NetApp Console muestra el asistente de la consola en la página de inicio para los usuarios nuevos que tienen el rol de administrador de la organización. Permanecerá disponible hasta que complete las tareas obligatorias de crear un agente de consola y agregar un sistema.

Usa el asistente para completar estas tareas, que proporcionan la configuración mínima para tu entorno de NetApp Console:

* Agregue una cuenta del sitio de soporte de NetApp (NSS).
+
link:task-adding-nss-accounts.html["Aprenda cómo agregar una cuenta NSS"].

* Conéctese a su patrimonio de almacenamiento implementando un agente de consola.
+
link:task-install-agent-on-prem.html["Aprenda a instalar un agente de consola local."]

* Administrar un sistema de almacenamiento agregando o descubriendo un clúster
* Agregue una suscripción de mercado o una licencia PAYGO.
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["Aprenda a agregar licencias y suscripciones"^].

* Revisar la información de los servicios de datos.

