= Agente de Console 4.6.0
:allow-uri-read: 




[[console-agent-4-6-0]]
=== Agente de Console 4.6.0

La versión 4.6.0 es compatible tanto con el modo estándar como con el modo restringido.

Esta versión del agente de la Console incluye mejoras de seguridad y correcciones de errores, así como la siguiente nueva función.

.Soporte para comprobaciones de configuración del espacio en disco necesario
Puedes validar que el espacio en disco necesario para el agente de la Console está disponible usando comprobaciones de configuración. Puedes realizar comprobaciones de configuración desde la Console o desde la consola de mantenimiento del Agent. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["Más información sobre la ejecución de comprobaciones de configuración en el agente de la consola"^]

.Actualiza un agente de consola desplegado en vCenter usando una ISO
Si desplegaste un agente de Console en vCenter usando un OVA, ahora puedes actualizarlo a una nueva versión montando una ISO en la VM y ejecutando la actualización desde la consola de mantenimiento de la VM. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Aprende cómo actualizar un agente de Console desplegado en vCenter"^]
