= 
:allow-uri-read: 


Después de instalar y configurar el agente de consola, agregue sus credenciales de nube para que el agente de consola tenga los permisos necesarios para realizar acciones en AWS o Azure.

[role="tabbed-block"]
====
.AWS
--
.Antes de empezar
Si acaba de crear estas credenciales de AWS, es posible que tarden unos minutos en estar disponibles.  Espere unos minutos antes de agregar las credenciales a la consola.

.Pasos
. Seleccione *Administración > Credenciales*.
. Seleccione *Credenciales de la organización*.
. Seleccione *Agregar credenciales* y siga los pasos del asistente.
+
.. *Ubicación de credenciales*: seleccione *Amazon Web Services > Agente.
.. *Definir credenciales*: ingrese una clave de acceso de AWS y una clave secreta.
.. *Suscripción al Marketplace*: asocie una suscripción al Marketplace con estas credenciales suscribiéndose ahora o seleccionando una suscripción existente.
.. *Revisar*: Confirme los detalles sobre las nuevas credenciales y seleccione *Agregar*.




Ya puedes ir a la https://console.netapp.com["NetApp Console"^] para comenzar a utilizar el agente de consola.

--
.Azur
--
.Antes de empezar
Si acaba de crear estas credenciales de Azure, es posible que tarden unos minutos en estar disponibles.  Espere unos minutos antes de agregar las credenciales del agente de consola.

.Pasos
. Seleccione *Administración > Credenciales*.
. Seleccione *Agregar credenciales* y siga los pasos del asistente.
+
.. *Ubicación de credenciales*: seleccione *Microsoft Azure > Agente*.
.. *Definir credenciales*: ingrese información sobre la entidad de servicio de Microsoft Entra que otorga los permisos necesarios:
+
*** ID de la aplicación (cliente)
*** ID de directorio (inquilino)
*** Secreto del cliente


.. *Suscripción al Marketplace*: asocie una suscripción al Marketplace con estas credenciales suscribiéndose ahora o seleccionando una suscripción existente.
.. *Revisar*: Confirme los detalles sobre las nuevas credenciales y seleccione *Agregar*.




.Resultado
El agente de consola ahora tiene los permisos que necesita para realizar acciones en Azure en su nombre.  Ya puedes ir a la https://console.netapp.com["NetApp Console"^] para comenzar a utilizar el agente de consola.

--
====