= 
:allow-uri-read: 


Si está utilizando una VPC compartida para implementar recursos en un proyecto de servicio, deberá preparar sus permisos.

Esta tabla es de referencia y su entorno debe reflejar la tabla de permisos cuando se complete la configuración de IAM.

.Ver permisos de VPC compartidos
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidad | Creador | Alojado en | Permisos del proyecto de servicio | Permisos del proyecto anfitrión | Objetivo 


| Cuenta de Google para implementar el agente | Costumbre | Proyecto de servicio  a| 
link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Política de implementación del agente"]
 a| 
computar.usuariodered
| Implementación del agente en el proyecto de servicio 


| cuenta de servicio del agente | Costumbre | Proyecto de servicio  a| 
link:reference-permissions-gcp.html["Política de cuenta de servicio del agente"]
| Compute.NetworkUser administrador de implementación.editor | Implementación y mantenimiento de Cloud Volumes ONTAP y los servicios en el proyecto de servicio 


| Cuenta de servicio de Cloud Volumes ONTAP | Costumbre | Proyecto de servicio | Miembro de storage.admin: cuenta de servicio de la NetApp Console como serviceAccount.user | N/A | (Opcional) Para NetApp Cloud Tiering y NetApp Backup and Recovery 


| Agente de servicio de las API de Google | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Interactúa con las API de Google Cloud en nombre de la implementación.  Permite que la consola utilice la red compartida. 


| Cuenta de servicio predeterminada de Google Compute Engine | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Implementa instancias de Google Cloud y la infraestructura computacional en nombre de la implementación.  Permite que la consola utilice la red compartida. 
|===
Notas:

. `deploymentmanager.editor` solo es necesario en el proyecto host si no pasas reglas de firewall al despliegue y eliges dejar que la Console las cree por ti. La NetApp Console crea un despliegue en el proyecto host que contiene la regla de firewall VPC0 si no se especifica ninguna regla.
. `firewall.create` y `firewall.delete` solo son necesarios si no pasas reglas de firewall a la implementación y eliges dejar que la Console las cree por ti. Estos permisos residen en el archivo .yaml de la cuenta de la Console. Si estás implementando un par de HA usando una VPC compartida, estos permisos se usarán para crear las reglas de firewall para VPC1, 2 y 3. Para todas las demás implementaciones, estos permisos también se usarán para crear reglas para VPC0.
. Para Cloud Tiering, la cuenta de servicio de tiering debe tener el rol `serviceAccount.user` en la cuenta de servicio, no solo a nivel de proyecto. Si asignas `serviceAccount.user` a nivel de proyecto, los permisos no se muestran cuando consultas la cuenta de servicio con `getIAMPolicy`.


====