= 
:allow-uri-read: 


Si está utilizando una VPC compartida para implementar recursos en un proyecto de servicio, deberá preparar sus permisos.

Esta tabla es de referencia y su entorno debe reflejar la tabla de permisos cuando se complete la configuración de IAM.

.Ver permisos de VPC compartidos
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidad | Creador | Alojado en | Permisos del proyecto de servicio | Permisos del proyecto anfitrión | Objetivo 


| Cuenta de Google para implementar el agente | Costumbre | Proyecto de servicio  a| 
link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Política de implementación del agente"]
 a| 
computar.usuariodered
| Implementación del agente en el proyecto de servicio 


| cuenta de servicio del agente | Costumbre | Proyecto de servicio  a| 
link:reference-permissions-gcp.html["Política de cuenta de servicio del agente"]
| Compute.NetworkUser administrador de implementación.editor | Implementación y mantenimiento de Cloud Volumes ONTAP y los servicios en el proyecto de servicio 


| Cuenta de servicio de Cloud Volumes ONTAP | Costumbre | Proyecto de servicio | Miembro de storage.admin: cuenta de servicio de la consola de NetApp como serviceAccount.user | N/A | (Opcional) Para NetApp Cloud Tiering y NetApp Backup and Recovery 


| Agente de servicio de las API de Google | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Interactúa con las API de Google Cloud en nombre de la implementación.  Permite que la consola utilice la red compartida. 


| Cuenta de servicio predeterminada de Google Compute Engine | Google Cloud | Proyecto de servicio  a| 
(Predeterminado) Editor
 a| 
computar.usuariodered
| Implementa instancias de Google Cloud y la infraestructura computacional en nombre de la implementación.  Permite que la consola utilice la red compartida. 
|===
Notas:

. deploymentmanager.editor solo es necesario en el proyecto host si no pasa reglas de firewall a la implementación y elige dejar que la consola las cree por usted.  La consola de NetApp crea una implementación en el proyecto de host que contiene la regla de firewall VPC0 si no se especifica ninguna regla.
. firewall.create y firewall.delete solo son necesarios si no pasa reglas de firewall a la implementación y elige dejar que la Consola las cree por usted.  Estos permisos residen en el archivo .yaml de la cuenta de la consola.  Si está implementando un par HA mediante una VPC compartida, estos permisos se utilizarán para crear las reglas de firewall para VPC1, 2 y 3.  Para todas las demás implementaciones, estos permisos también se utilizarán para crear reglas para VPC0.
. Para la organización en niveles de nube, la cuenta de servicio de organización en niveles debe tener el rol serviceAccount.user en la cuenta de servicio, no solo en el nivel de proyecto.  Actualmente, si asigna serviceAccount.user en el nivel del proyecto, los permisos no se muestran cuando consulta la cuenta de servicio con getIAMPolicy.


====