= 
:allow-uri-read: 


Crea un rol y aplícalo a una cuenta de servicio que usarás para la instancia de VM del agente de consola.

.Pasos
. Crear un rol personalizado en Google Cloud:
+
.. Cree un archivo YAML que incluya los permisos definidos en ellink:reference-permissions-gcp.html["Política del agente de consola para Google Cloud"] .
.. Desde Google Cloud, activa Cloud Shell.
.. Cargue el archivo YAML que incluye los permisos necesarios para el agente de consola.
.. Cree un rol personalizado mediante el uso de `gcloud iam roles create` dominio.
+
El siguiente ejemplo crea un rol denominado "conector" a nivel de proyecto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentación de Google Cloud: Creación y administración de roles personalizados"^]



. Crear una cuenta de servicio en Google Cloud:
+
.. Desde el servicio IAM y administración, seleccione *Cuentas de servicio > Crear cuenta de servicio*.
.. Ingrese los detalles de la cuenta de servicio y seleccione *Crear y continuar*.
.. Seleccione el rol que acaba de crear.
.. Complete los pasos restantes para crear el rol.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentación de Google Cloud: Creación de una cuenta de servicio"^]





.Resultado
Ahora tiene una cuenta de servicio que puede asignar a la instancia de VM del agente de consola.
