= 
:allow-uri-read: 


.Antes de empezar
Debes tener lo siguiente:

* Privilegios de root para instalar el agente de consola.
* Detalles sobre un servidor proxy, si se requiere un proxy para el acceso a Internet desde el agente de la consola.
+
Tiene la opción de configurar un servidor proxy después de la instalación, pero para hacerlo es necesario reiniciar el agente de la consola.

* Un certificado firmado por una CA, si el servidor proxy usa HTTPS o si el proxy es un proxy interceptor.



NOTE: No es posible configurar un certificado para un servidor proxy transparente al instalar manualmente el agente de consola. Si necesita configurar un certificado para un servidor proxy transparente, debe utilizar la Consola de mantenimiento después de la instalación. Obtén más información sobre link:reference-agent-maint-console-proxy.html["Consola de mantenimiento del agente"].

.Acerca de esta tarea
Después de la instalación, el agente de consola se actualiza automáticamente si hay una nueva versión disponible.

.Pasos
. Si las variables del sistema _http_proxy_ o _https_proxy_ están configuradas en el host, elimínelas:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si no elimina estas variables del sistema, la instalación fallará.

. Descargue el software del agente de consola y luego cópielo al host Linux.  Puede descargarlo desde la NetApp Console o desde el sitio de soporte de NetApp .
+
** NetApp Console: vaya a *Agentes > Administración > Implementar agente > Local > Instalación manual*.
+
Elija descargar los archivos de instalación del agente o una URL a los archivos.

** Sitio de soporte de NetApp (necesario si aún no tiene acceso a la consola) https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["Sitio de soporte de NetApp"^] ,


. Asignar permisos para ejecutar el script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Donde <versión> es la versión del agente de consola que descargó.

. Si realiza la instalación en un entorno de nube gubernamental, desactive las comprobaciones de configuración.link:task-troubleshoot-agent.html#disable-config-check["Aprenda cómo deshabilitar las comprobaciones de configuración para instalaciones manuales."]
. Ejecute el script de instalación.
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Tendrás que añadir información del proxy si tu red requiere un proxy para acceder a internet. Puedes añadir un proxy explícito durante la instalación. Los parámetros `--proxy` y `--cacert` son opcionales y no se te pedirá que los añadas. Si tienes un servidor proxy explícito, tendrás que ingresar los parámetros como se muestra.




NOTE: Si quieres configurar un proxy transparente, puedes hacerlo después de la instalación. link:reference-agent-maint-console-proxy.html["Obtenga información sobre la consola de mantenimiento del agente."]

+

A continuación se muestra un ejemplo de configuración de un servidor proxy explícito con un certificado firmado por una CA:

+

[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` configura el agente de Console para usar un servidor proxy HTTP o HTTPS usando uno de los siguientes formatos:

+ * \http://address:port * \http://user-name:password@address:port * \http://domain-name%92user-name:password@address:port * \https://address:port * \https://user-name:password@address:port * \https://domain-name%92user-name:password@address:port

+ Ten en cuenta lo siguiente:

+ ** El usuario puede ser un usuario local o un usuario de dominio. ** Para un usuario de dominio, debes usar el código ASCII para una \ como se muestra arriba. ** El agente de la Console no admite nombres de usuario ni contraseñas que incluyan el carácter @. ** Si la contraseña incluye cualquiera de los siguientes caracteres especiales, debes escapar ese carácter especial anteponiéndole una barra invertida: & o !

+ Por ejemplo:

+ \http://bxpproxyuser:netapp1\!@dirección:3128

. Si utilizó Podman, necesitará ajustar el puerto aardvark-dns.
+
.. SSH a la máquina virtual del agente de consola.
.. Abra el archivo podman _/usr/share/containers/containers.conf_ y modifique el puerto elegido para el servicio DNS de Aardvark.  Por ejemplo, cámbielo a 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
Por ejemplo:

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. Reinicie la máquina virtual del agente de consola.




. Espere a que se complete la instalación.
+
Al final de la instalación, el servicio del agente de consola (occm) se reinicia dos veces si especificó un servidor proxy.




NOTE: Si la instalación falla, puede ver el informe de instalación y los registros para ayudarlo a solucionar los problemas.link:task-troubleshoot-agent.html#troubleshoot-installation["Aprenda a solucionar problemas de instalación."]

. Abra un navegador web desde un host que tenga una conexión a la máquina virtual del agente de consola e ingrese la siguiente URL:
+
https://_ipaddress_[]

. Después de iniciar sesión, configure el agente de la consola:
+
.. Especifique la organización que se asociará con el agente de la consola.
.. Introduzca un nombre para el sistema.
.. En *¿Está ejecutando en un entorno seguro?* mantenga el modo restringido deshabilitado.
+
Debes mantener el modo restringido deshabilitado porque estos pasos describen cómo usar la consola en modo estándar.  Debe habilitar el modo restringido solo si tiene un entorno seguro y desea desconectar esta cuenta de los servicios de backend.  Si ese es el caso,link:task-quick-start-restricted-mode.html["Siga los pasos para comenzar a utilizar la NetApp Console en modo restringido"] .

.. Seleccione *Comencemos*.



